//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SolucionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SolucionResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SolucionResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An exclusive community website to communicate,.
        /// </summary>
        internal static string Comunicacion_Descripcion_Linea1 {
            get {
                return ResourceManager.GetString("Comunicacion_Descripcion_Linea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a participate, vote online, reserve areas, and more.
        /// </summary>
        internal static string Comunicacion_Descripcion_Linea2 {
            get {
                return ResourceManager.GetString("Comunicacion_Descripcion_Linea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3. Connectivity and communication.
        /// </summary>
        internal static string Comunicacion_Header {
            get {
                return ResourceManager.GetString("Comunicacion_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Communication and Participation.
        /// </summary>
        internal static string Comunicacion_Left_Linea1 {
            get {
                return ResourceManager.GetString("Comunicacion_Left_Linea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a from Internet.
        /// </summary>
        internal static string Comunicacion_Left_Linea2 {
            get {
                return ResourceManager.GetString("Comunicacion_Left_Linea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finally from the Web!.
        /// </summary>
        internal static string Comunicacion_RibbonBottom_Linea1 {
            get {
                return ResourceManager.GetString("Comunicacion_RibbonBottom_Linea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The dynamics of the condominium, without meetings, without withdrawal, with participation..
        /// </summary>
        internal static string Comunicacion_RibbonBottom_Linea2 {
            get {
                return ResourceManager.GetString("Comunicacion_RibbonBottom_Linea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a For emergencies, relevant information and invitations to owners, sent from the web..
        /// </summary>
        internal static string Comunicacion_Right_Opcion1_Contenido1 {
            get {
                return ResourceManager.GetString("Comunicacion_Right_Opcion1_Contenido1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send bulk SMS..
        /// </summary>
        internal static string Comunicacion_Right_Opcion1_Header {
            get {
                return ResourceManager.GetString("Comunicacion_Right_Opcion1_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Watchers and the access to those responsible. This information and much more, available in the cloud, it can be sent by email or SMS accordingly..
        /// </summary>
        internal static string Comunicacion_Right_Opcion2_Contenido1 {
            get {
                return ResourceManager.GetString("Comunicacion_Right_Opcion2_Contenido1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record of all system activity.
        /// </summary>
        internal static string Comunicacion_Right_Opcion2_Header {
            get {
                return ResourceManager.GetString("Comunicacion_Right_Opcion2_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An exclusive community website to communicate, participate in forums, reserve areas and to vote with a single click, from your computer, among others..
        /// </summary>
        internal static string Comunicacion_Right_Opcion3_Contenido1 {
            get {
                return ResourceManager.GetString("Comunicacion_Right_Opcion3_Contenido1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a virtual condo.
        /// </summary>
        internal static string Comunicacion_Right_Opcion3_Header {
            get {
                return ResourceManager.GetString("Comunicacion_Right_Opcion3_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reduce the dedication and achieve much more than their neighbors through services designed for meetings..
        /// </summary>
        internal static string Comunicacion_Right_Opcion4_Contenido1 {
            get {
                return ResourceManager.GetString("Comunicacion_Right_Opcion4_Contenido1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Benefits for neighbors or condo boards.
        /// </summary>
        internal static string Comunicacion_Right_Opcion4_Header {
            get {
                return ResourceManager.GetString("Comunicacion_Right_Opcion4_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Both use only &quot;non-transferable&quot; methods of validating.
        /// </summary>
        internal static string ControlAcceso_Descripcion_Linea1 {
            get {
                return ResourceManager.GetString("ControlAcceso_Descripcion_Linea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a identity, telephone and biometric access. Elimiando the risk.
        /// </summary>
        internal static string ControlAcceso_Descripcion_Linea2 {
            get {
                return ResourceManager.GetString("ControlAcceso_Descripcion_Linea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a of traditional physical accessories like keys, checks and cards.
        /// </summary>
        internal static string ControlAcceso_Descripcion_Linea3 {
            get {
                return ResourceManager.GetString("ControlAcceso_Descripcion_Linea3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a among others, which may fall into the wrong hands..
        /// </summary>
        internal static string ControlAcceso_Descripcion_Linea4 {
            get {
                return ResourceManager.GetString("ControlAcceso_Descripcion_Linea4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1. Total Access Control.
        /// </summary>
        internal static string ControlAcceso_Header1 {
            get {
                return ResourceManager.GetString("ControlAcceso_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a With a free call, or with your footprint, open doors and gates.
        /// </summary>
        internal static string ControlAcceso_Left_Message {
            get {
                return ResourceManager.GetString("ControlAcceso_Left_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a But also, look!.
        /// </summary>
        internal static string ControlAcceso_RibbonBottom_Linea1 {
            get {
                return ResourceManager.GetString("ControlAcceso_RibbonBottom_Linea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a They are the most convenient ways to get in and out of your house!.
        /// </summary>
        internal static string ControlAcceso_RibbonBottom_Linea2 {
            get {
                return ResourceManager.GetString("ControlAcceso_RibbonBottom_Linea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a With Seguricel, only you have the key ....
        /// </summary>
        internal static string ControlAcceso_Right_Footer {
            get {
                return ResourceManager.GetString("ControlAcceso_Right_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evolution with unique features.
        /// </summary>
        internal static string ControlAcceso_Right_Header {
            get {
                return ResourceManager.GetString("ControlAcceso_Right_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uncopyable safe and comfortable..
        /// </summary>
        internal static string ControlAcceso_Right_Opcion1 {
            get {
                return ResourceManager.GetString("ControlAcceso_Right_Opcion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only community members can open doors.
        /// </summary>
        internal static string ControlAcceso_Right_Opcion2 {
            get {
                return ResourceManager.GetString("ControlAcceso_Right_Opcion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All activation is recorded.
        /// </summary>
        internal static string ControlAcceso_Right_Opcion3 {
            get {
                return ResourceManager.GetString("ControlAcceso_Right_Opcion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Self-management: each family manages its list of authorized.
        /// </summary>
        internal static string ControlAcceso_Right_Opcion4 {
            get {
                return ResourceManager.GetString("ControlAcceso_Right_Opcion4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Communication.
        /// </summary>
        internal static string HeaderComunicacion {
            get {
                return ResourceManager.GetString("HeaderComunicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Safety.
        /// </summary>
        internal static string HeaderLine1_1 {
            get {
                return ResourceManager.GetString("HeaderLine1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a in residential complexes.
        /// </summary>
        internal static string HeaderLine1_2 {
            get {
                return ResourceManager.GetString("HeaderLine1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a is based on three pillars.
        /// </summary>
        internal static string HeaderLine2_1 {
            get {
                return ResourceManager.GetString("HeaderLine2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string HeaderLine2_2 {
            get {
                return ResourceManager.GetString("HeaderLine2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Un conjunto de dispositivos y un sistema web interactuando con el.
        /// </summary>
        internal static string Vigilante_Descripcion_Linea1 {
            get {
                return ResourceManager.GetString("Vigilante_Descripcion_Linea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a support, control and monitor performance.
        /// </summary>
        internal static string Vigilante_Descripcion_Linea2 {
            get {
                return ResourceManager.GetString("Vigilante_Descripcion_Linea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2. Monitoring responsible and productive.
        /// </summary>
        internal static string Vigilante_Header {
            get {
                return ResourceManager.GetString("Vigilante_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capitalizing on your monthly investment in security.
        /// </summary>
        internal static string Vigilante_RibbonBottom_Linea1 {
            get {
                return ResourceManager.GetString("Vigilante_RibbonBottom_Linea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a With technology that offers performance effectiveness and performance.
        /// </summary>
        internal static string Vigilante_RibbonBottom_Linea2 {
            get {
                return ResourceManager.GetString("Vigilante_RibbonBottom_Linea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An intelligent terminal as the only tool for access and management control..
        /// </summary>
        internal static string Vigilante_Right_Opcion1_Contenido1 {
            get {
                return ResourceManager.GetString("Vigilante_Right_Opcion1_Contenido1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only after having documented the visit will open the door and immediately notify the owner of the visitor&apos;s arrival by SMS..
        /// </summary>
        internal static string Vigilante_Right_Opcion1_Contenido2 {
            get {
                return ResourceManager.GetString("Vigilante_Right_Opcion1_Contenido2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Controlled access..
        /// </summary>
        internal static string Vigilante_Right_Opcion1_Header {
            get {
                return ResourceManager.GetString("Vigilante_Right_Opcion1_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Automated monitoring system to keep attentive staff 24 hours. Interacting with staff and reporting in real-time or scheduled to those concerned incidents or faults..
        /// </summary>
        internal static string Vigilante_Right_Opcion2_Contenido1 {
            get {
                return ResourceManager.GetString("Vigilante_Right_Opcion2_Contenido1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Always alert.
        /// </summary>
        internal static string Vigilante_Right_Opcion2_Header {
            get {
                return ResourceManager.GetString("Vigilante_Right_Opcion2_Header", resourceCulture);
            }
        }
    }
}
