//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContratosResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContratosResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Seguricel3.App_GlobalResources.Contratos.ContratosResource", typeof(ContratosResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        public static string ButtonNewContent {
            get {
                return ResourceManager.GetString("ButtonNewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Contrato.
        /// </summary>
        public static string CreateHeaderPage {
            get {
                return ResourceManager.GetString("CreateHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Nuevo Contrato.
        /// </summary>
        public static string CreatePageTitle {
            get {
                return ResourceManager.GetString("CreatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Contrato.
        /// </summary>
        public static string DeleteHeaderPage {
            get {
                return ResourceManager.GetString("DeleteHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Eliminar Contrato.
        /// </summary>
        public static string DeletePageTitle {
            get {
                return ResourceManager.GetString("DeletePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Contrato.
        /// </summary>
        public static string EditHeaderPage {
            get {
                return ResourceManager.GetString("EditHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Actualizar Contrato.
        /// </summary>
        public static string EditPageTitle {
            get {
                return ResourceManager.GetString("EditPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimiento de Contratos.
        /// </summary>
        public static string HeaderPage {
            get {
                return ResourceManager.GetString("HeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso Biométrico.
        /// </summary>
        public static string LabelAccesoDactilar {
            get {
                return ResourceManager.GetString("LabelAccesoDactilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso Telefónico.
        /// </summary>
        public static string LabelAccesoTelefonico {
            get {
                return ResourceManager.GetString("LabelAccesoTelefonico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administradora.
        /// </summary>
        public static string LabelAdministradora {
            get {
                return ResourceManager.GetString("LabelAdministradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alarma Silente.
        /// </summary>
        public static string LabelAlarmaSilente {
            get {
                return ResourceManager.GetString("LabelAlarmaSilente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestionado por Contratante.
        /// </summary>
        public static string LabelAutoGestion {
            get {
                return ResourceManager.GetString("LabelAutoGestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autogestion de Apartamentos.
        /// </summary>
        public static string LabelAutoGestion_Aptos {
            get {
                return ResourceManager.GetString("LabelAutoGestion_Aptos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        public static string LabelCiudad {
            get {
                return ResourceManager.GetString("LabelCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Postal.
        /// </summary>
        public static string LabelCodigoPostal {
            get {
                return ResourceManager.GetString("LabelCodigoPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Condominio Virtual.
        /// </summary>
        public static string LabelCondominioVirtual {
            get {
                return ResourceManager.GetString("LabelCondominioVirtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña Usuario Correo Comunidad.
        /// </summary>
        public static string LabelContraseñaCorreoComunidad {
            get {
                return ResourceManager.GetString("LabelContraseñaCorreoComunidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña Correo Junta Condominio.
        /// </summary>
        public static string LabelContraseñaCorreoJC {
            get {
                return ResourceManager.GetString("LabelContraseñaCorreoJC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contratante.
        /// </summary>
        public static string LabelContratante {
            get {
                return ResourceManager.GetString("LabelContratante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato.
        /// </summary>
        public static string LabelContrato {
            get {
                return ResourceManager.GetString("LabelContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control de Ascensores.
        /// </summary>
        public static string LabelControlAscensores {
            get {
                return ResourceManager.GetString("LabelControlAscensores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control de Estacionamiento.
        /// </summary>
        public static string LabelControlEstacionamiento {
            get {
                return ResourceManager.GetString("LabelControlEstacionamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico de la Comunidad.
        /// </summary>
        public static string LabelCorreoElectronicoComunida {
            get {
                return ResourceManager.GetString("LabelCorreoElectronicoComunida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico de la Junta.
        /// </summary>
        public static string LabelCorreoElectronicoJunta {
            get {
                return ResourceManager.GetString("LabelCorreoElectronicoJunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detiene SMS para Junta de Condominio.
        /// </summary>
        public static string LabelDetieneSMS_JC {
            get {
                return ResourceManager.GetString("LabelDetieneSMS_JC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación.
        /// </summary>
        public static string LabelDireccion {
            get {
                return ResourceManager.GetString("LabelDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Emergencia Vecinal.
        /// </summary>
        public static string LabelEmergenciaVecinal {
            get {
                return ResourceManager.GetString("LabelEmergenciaVecinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string LabelEstado {
            get {
                return ResourceManager.GetString("LabelEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Contrato.
        /// </summary>
        public static string LabelEstadoContrato {
            get {
                return ResourceManager.GetString("LabelEstadoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Contrato.
        /// </summary>
        public static string LabelFechaContrato {
            get {
                return ResourceManager.GetString("LabelFechaContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pan Id para Red Miwi.
        /// </summary>
        public static string LabelIdRedMiwi {
            get {
                return ResourceManager.GetString("LabelIdRedMiwi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen del Edificio.
        /// </summary>
        public static string LabelImagenEdificio {
            get {
                return ResourceManager.GetString("LabelImagenEdificio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Latitud.
        /// </summary>
        public static string LabelLatitud {
            get {
                return ResourceManager.GetString("LabelLatitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud.
        /// </summary>
        public static string LabelLongitud {
            get {
                return ResourceManager.GetString("LabelLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Invitados por Unidad.
        /// </summary>
        public static string LabelMaximoInvitados {
            get {
                return ResourceManager.GetString("LabelMaximoInvitados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. Maximo Puestos Fijos.
        /// </summary>
        public static string LabelMaximoPuestosFijos {
            get {
                return ResourceManager.GetString("LabelMaximoPuestosFijos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. Máximo Puestos Visitantes.
        /// </summary>
        public static string LabelMaximoPuestosVisitantes {
            get {
                return ResourceManager.GetString("LabelMaximoPuestosVisitantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Secundarios por Unidad.
        /// </summary>
        public static string LabelMaximoSecundarios {
            get {
                return ResourceManager.GetString("LabelMaximoSecundarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mes de Corte.
        /// </summary>
        public static string LabelMesCorte {
            get {
                return ResourceManager.GetString("LabelMesCorte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Completo Contratante.
        /// </summary>
        public static string LabelNombreCompleto {
            get {
                return ResourceManager.GetString("LabelNombreCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. Contrato.
        /// </summary>
        public static string LabelNroContrato {
            get {
                return ResourceManager.GetString("LabelNroContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nro Redes Instalación.
        /// </summary>
        public static string LabelNroRedesInstalacion {
            get {
                return ResourceManager.GetString("LabelNroRedesInstalacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        public static string LabelPais {
            get {
                return ResourceManager.GetString("LabelPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puerto POP3 Comunidad.
        /// </summary>
        public static string LabelPuertoPOPGeneral {
            get {
                return ResourceManager.GetString("LabelPuertoPOPGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puerto POP3 Junta Condominio.
        /// </summary>
        public static string LabelPuertoPOPJC {
            get {
                return ResourceManager.GetString("LabelPuertoPOPJC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puerto SMTP Comunidad.
        /// </summary>
        public static string LabelPuertoSMTPGeneral {
            get {
                return ResourceManager.GetString("LabelPuertoSMTPGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puerto SMTP Junta Condominio.
        /// </summary>
        public static string LabelPuertoSMTPJC {
            get {
                return ResourceManager.GetString("LabelPuertoSMTPJC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RIF.
        /// </summary>
        public static string LabelRegistroFiscal {
            get {
                return ResourceManager.GetString("LabelRegistroFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servidor para POP3 Comunidad.
        /// </summary>
        public static string LabelServidorPOPGeneral {
            get {
                return ResourceManager.GetString("LabelServidorPOPGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servidor para POP3 Junta Condominio.
        /// </summary>
        public static string LabelServidorPOPJC {
            get {
                return ResourceManager.GetString("LabelServidorPOPJC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servidor para SMTP Comunidad.
        /// </summary>
        public static string LabelServidorSMTPGeneral {
            get {
                return ResourceManager.GetString("LabelServidorSMTPGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servidor para SMTP Junta Condominio.
        /// </summary>
        public static string LabelServidorSMTPJC {
            get {
                return ResourceManager.GetString("LabelServidorSMTPJC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Contrato.
        /// </summary>
        public static string LabelTipoContrato {
            get {
                return ResourceManager.GetString("LabelTipoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicacion Geografica.
        /// </summary>
        public static string LabelUbicacionGeografica {
            get {
                return ResourceManager.GetString("LabelUbicacionGeografica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario Correo Comunidad.
        /// </summary>
        public static string LabelUsuarioCorreoComunidad {
            get {
                return ResourceManager.GetString("LabelUsuarioCorreoComunidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario Correo Junta Condominio.
        /// </summary>
        public static string LabelUsuarioCorreoJC {
            get {
                return ResourceManager.GetString("LabelUsuarioCorreoJC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vigicel / Vigimovil.
        /// </summary>
        public static string LabelVigicel {
            get {
                return ResourceManager.GetString("LabelVigicel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Mantenimiento de Contratos.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información del Contrato.
        /// </summary>
        public static string ShowHeaderPage {
            get {
                return ResourceManager.GetString("ShowHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Información del Contrato.
        /// </summary>
        public static string ShowPageTitle {
            get {
                return ResourceManager.GetString("ShowPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Contratos.
        /// </summary>
        public static string TableHeader {
            get {
                return ResourceManager.GetString("TableHeader", resourceCulture);
            }
        }
    }
}
