//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContratoUnidadResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContratoUnidadResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Seguricel3.App_GlobalResources.Contratos.ContratoUnidadResource", typeof(ContratoUnidadResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Unidad.
        /// </summary>
        public static string CreateHeaderPage {
            get {
                return ResourceManager.GetString("CreateHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Nueva Unidad.
        /// </summary>
        public static string CreatePageTitle {
            get {
                return ResourceManager.GetString("CreatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede eliminar la unidad. Tiene registros asociados..
        /// </summary>
        public static string DeleteErrorMessage {
            get {
                return ResourceManager.GetString("DeleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Unidad.
        /// </summary>
        public static string EditHeaderPage {
            get {
                return ResourceManager.GetString("EditHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Actualizar Unidad.
        /// </summary>
        public static string EditPageTitle {
            get {
                return ResourceManager.GetString("EditPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimiento de Unidad.
        /// </summary>
        public static string HeaderPage {
            get {
                return ResourceManager.GetString("HeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activa.
        /// </summary>
        public static string labelActiva {
            get {
                return ResourceManager.GetString("labelActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Autorización.
        /// </summary>
        public static string labelCodigoAutorizacion {
            get {
                return ResourceManager.GetString("labelCodigoAutorizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato.
        /// </summary>
        public static string LabelContrato {
            get {
                return ResourceManager.GetString("LabelContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación de la Unidad.
        /// </summary>
        public static string labelIdentificacion {
            get {
                return ResourceManager.GetString("labelIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código para Vigilancia.
        /// </summary>
        public static string labelIdentificaciónVigilancia {
            get {
                return ResourceManager.GetString("labelIdentificaciónVigilancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen para Mensajería.
        /// </summary>
        public static string labelImagen {
            get {
                return ResourceManager.GetString("labelImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AceptaInvitados.
        /// </summary>
        public static string labelInvitados {
            get {
                return ResourceManager.GetString("labelInvitados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pertenece a Junta de Condominio.
        /// </summary>
        public static string labelJuntaCondominio {
            get {
                return ResourceManager.GetString("labelJuntaCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string labelNombre {
            get {
                return ResourceManager.GetString("labelNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acepta Secundarios.
        /// </summary>
        public static string labelNroSecundarios {
            get {
                return ResourceManager.GetString("labelNroSecundarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        public static string labelPais {
            get {
                return ResourceManager.GetString("labelPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piso.
        /// </summary>
        public static string labelPiso {
            get {
                return ResourceManager.GetString("labelPiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permitir acceso por Vigilantes.
        /// </summary>
        public static string labelSeguridad {
            get {
                return ResourceManager.GetString("labelSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Torre.
        /// </summary>
        public static string labelTorre {
            get {
                return ResourceManager.GetString("labelTorre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad Maestra.
        /// </summary>
        public static string labelUnidadMaestra {
            get {
                return ResourceManager.GetString("labelUnidadMaestra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activar Modo Vacaciones.
        /// </summary>
        public static string labelVacaciones {
            get {
                return ResourceManager.GetString("labelVacaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Mantenimiento de Unidad.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de la Unidad.
        /// </summary>
        public static string ShowHeaderPage {
            get {
                return ResourceManager.GetString("ShowHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Información de la Unidad.
        /// </summary>
        public static string ShowPageTitle {
            get {
                return ResourceManager.GetString("ShowPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Unidades.
        /// </summary>
        public static string TableHeader {
            get {
                return ResourceManager.GetString("TableHeader", resourceCulture);
            }
        }
    }
}
