//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoginResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Seguricel3.App_GlobalResources.Account.Login.LoginResource", typeof(LoginResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesión.
        /// </summary>
        public static string CloseSessionLabel {
            get {
                return ResourceManager.GetString("CloseSessionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string CodeLabel {
            get {
                return ResourceManager.GetString("CodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe Indicar el código de usuario.
        /// </summary>
        public static string CodeRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CodeRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña y la contraseña de confirmación no coinciden..
        /// </summary>
        public static string ConfirmarContraseñaCompareErrorMessage {
            get {
                return ResourceManager.GetString("ConfirmarContraseñaCompareErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string ConfirmarContraseñaLabel {
            get {
                return ResourceManager.GetString("ConfirmarContraseñaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de caracteres de {0} debe ser al menos {2}.
        /// </summary>
        public static string ContraseñaStringLengthErrorMessage {
            get {
                return ResourceManager.GetString("ContraseñaStringLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico indicado no es válido.
        /// </summary>
        public static string EmailAddressErrorMessge {
            get {
                return ResourceManager.GetString("EmailAddressErrorMessge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe indicar el correo electrónico.
        /// </summary>
        public static string EmailRequiredErrorMessage {
            get {
                return ResourceManager.GetString("EmailRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Ha olvidado su contraseña?.
        /// </summary>
        public static string ForgotPasswordText {
            get {
                return ResourceManager.GetString("ForgotPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para brindarle la mejor experiencia posible, además de crear un sitio más seguro y confiable, utilizamos cookies. El uso de Seguricel.com significa que Ud. está otorgando su consentimiento para que las cookies sean utilizadas. Hemos publicado una nueva política de cookies, la cual le permitirá conocer más sobre nuestras cookies..
        /// </summary>
        public static string LoginCookieClientMessage {
            get {
                return ResourceManager.GetString("LoginCookieClientMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico y/o la contraseña no son correctos..
        /// </summary>
        public static string LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario se encuentra bloqueado. Comuniquese con la Junta de Condominio..
        /// </summary>
        public static string LoginFailedMessageBloqueado {
            get {
                return ResourceManager.GetString("LoginFailedMessageBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario se encuentra inactivo.
        /// </summary>
        public static string LoginFailedMessageInactivo {
            get {
                return ResourceManager.GetString("LoginFailedMessageInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use su cuenta de usuario para iniciar sesión..
        /// </summary>
        public static string LoginSubTitle {
            get {
                return ResourceManager.GetString("LoginSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe indicar su contraseña.
        /// </summary>
        public static string PasswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        public static string ProviderLabel {
            get {
                return ResourceManager.GetString("ProviderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe indicar el proveedor.
        /// </summary>
        public static string ProviderRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ProviderRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Recordar cuenta?.
        /// </summary>
        public static string RecordarCuentaLabel {
            get {
                return ResourceManager.GetString("RecordarCuentaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar como nuevo usuario.
        /// </summary>
        public static string RegistrarNuevoUsuarioLabel {
            get {
                return ResourceManager.GetString("RegistrarNuevoUsuarioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Recordar este explorador?.
        /// </summary>
        public static string RememberBrowserLabel {
            get {
                return ResourceManager.GetString("RememberBrowserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string submitButtonText {
            get {
                return ResourceManager.GetString("submitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verifique los errores que se muestran en la página.
        /// </summary>
        public static string ValidationSummaryText {
            get {
                return ResourceManager.GetString("ValidationSummaryText", resourceCulture);
            }
        }
    }
}
