//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CotizacionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CotizacionResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Seguricel3.App_GlobalResources.Ventas.Cotizacion.CotizacionResource", typeof(CotizacionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Cotización.
        /// </summary>
        public static string CreateHeaderPage {
            get {
                return ResourceManager.GetString("CreateHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar una Cotización.
        /// </summary>
        public static string CreatePageTitle {
            get {
                return ResourceManager.GetString("CreatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cotizaciones.
        /// </summary>
        public static string HeaderPage {
            get {
                return ResourceManager.GetString("HeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso Biométrico.
        /// </summary>
        public static string labelAccesoBiometrico {
            get {
                return ResourceManager.GetString("labelAccesoBiometrico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Acceso.
        /// </summary>
        public static string labelAccesoNombre {
            get {
                return ResourceManager.GetString("labelAccesoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso por RFID.
        /// </summary>
        public static string labelAccesoRFID {
            get {
                return ResourceManager.GetString("labelAccesoRFID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso Telefónico.
        /// </summary>
        public static string labelAccesoTelefono {
            get {
                return ResourceManager.GetString("labelAccesoTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso.
        /// </summary>
        public static string labelAccesoTitle {
            get {
                return ResourceManager.GetString("labelAccesoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alarma Silente.
        /// </summary>
        public static string labelAlarmaSilente {
            get {
                return ResourceManager.GetString("labelAlarmaSilente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. de Dispositivos.
        /// </summary>
        public static string labelCantidadDispositivo {
            get {
                return ResourceManager.GetString("labelCantidadDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        public static string labelCiudad {
            get {
                return ResourceManager.GetString("labelCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        public static string labelContactoTitle {
            get {
                return ResourceManager.GetString("labelContactoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrada.
        /// </summary>
        public static string labelControlEntrada {
            get {
                return ResourceManager.GetString("labelControlEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salida.
        /// </summary>
        public static string labelControlSalida {
            get {
                return ResourceManager.GetString("labelControlSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control de Vigilancia.
        /// </summary>
        public static string labelControlVigilancia {
            get {
                return ResourceManager.GetString("labelControlVigilancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción Acceso Actual.
        /// </summary>
        public static string labelDescripcionAccesoActual {
            get {
                return ResourceManager.GetString("labelDescripcionAccesoActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string labelDireccion {
            get {
                return ResourceManager.GetString("labelDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa de Vigilancia.
        /// </summary>
        public static string labelEmpresaVigilancia {
            get {
                return ResourceManager.GetString("labelEmpresaVigilancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string labelEstado {
            get {
                return ResourceManager.GetString("labelEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de la Propuesta.
        /// </summary>
        public static string labelEstadoPropuesta {
            get {
                return ResourceManager.GetString("labelEstadoPropuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Último Estado.
        /// </summary>
        public static string labelFechaEstadoPropuesta {
            get {
                return ResourceManager.GetString("labelFechaEstadoPropuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Registro.
        /// </summary>
        public static string labelFechaRegistro {
            get {
                return ResourceManager.GetString("labelFechaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. Locales Comerciales.
        /// </summary>
        public static string labelLocales {
            get {
                return ResourceManager.GetString("labelLocales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string labelNombre {
            get {
                return ResourceManager.GetString("labelNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Contacto.
        /// </summary>
        public static string labelNombreContacto {
            get {
                return ResourceManager.GetString("labelNombreContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        public static string labelPais {
            get {
                return ResourceManager.GetString("labelPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. de Unidades por Torre.
        /// </summary>
        public static string labelResidencias {
            get {
                return ResourceManager.GetString("labelResidencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. Teléfono Fijo.
        /// </summary>
        public static string labelTelefonoContacto1 {
            get {
                return ResourceManager.GetString("labelTelefonoContacto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. Teléfono Móvil.
        /// </summary>
        public static string labelTelefonoContacto2 {
            get {
                return ResourceManager.GetString("labelTelefonoContacto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Dispositivo.
        /// </summary>
        public static string labelTipoDispositivo {
            get {
                return ResourceManager.GetString("labelTipoDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Propuesta.
        /// </summary>
        public static string labelTipoPropuesta {
            get {
                return ResourceManager.GetString("labelTipoPropuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. de Torres.
        /// </summary>
        public static string labelTorres {
            get {
                return ResourceManager.GetString("labelTorres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total de Residencias.
        /// </summary>
        public static string labelTotalResidencia {
            get {
                return ResourceManager.GetString("labelTotalResidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vendedor.
        /// </summary>
        public static string labelVendedor {
            get {
                return ResourceManager.GetString("labelVendedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vgilancia Contratada.
        /// </summary>
        public static string labelVigilanciaContratada {
            get {
                return ResourceManager.GetString("labelVigilanciaContratada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Cotizaciones.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Cotizaciones.
        /// </summary>
        public static string TableHeader {
            get {
                return ResourceManager.GetString("TableHeader", resourceCulture);
            }
        }
    }
}
