//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato_Unidad_Anuncio
    {
        public System.Guid IdContrato { get; set; }
        public System.Guid IdUnidad { get; set; }
        public System.Guid IdAnuncio { get; set; }
        public System.DateTime FechaAnuncio { get; set; }
        public int IdTipoAnuncio { get; set; }
        public string Anuncio { get; set; }
        public int VotosPositivos { get; set; }
        public int VotosNegativos { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual Contrato_Unidad Contrato_Unidad { get; set; }
        public virtual TipoAnuncio TipoAnuncio { get; set; }
    }
}
