//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato_Unidad_Persona_AlarmaSilente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato_Unidad_Persona_AlarmaSilente()
        {
            this.Contrato_Unidad_Persona_AlarmaSilente_Bitacora = new HashSet<Contrato_Unidad_Persona_AlarmaSilente_Bitacora>();
        }
    
        public System.Guid IdContrato { get; set; }
        public System.Guid IdUnidad { get; set; }
        public System.Guid IdPersona { get; set; }
        public System.Guid IdAlarmaSilente { get; set; }
        public string Nombre { get; set; }
        public string NroTelefono { get; set; }
        public string Mensaje { get; set; }
    
        public virtual Contrato_Unidad_Persona Contrato_Unidad_Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Unidad_Persona_AlarmaSilente_Bitacora> Contrato_Unidad_Persona_AlarmaSilente_Bitacora { get; set; }
        public virtual Contrato Contrato { get; set; }
        public virtual Contrato_Unidad Contrato_Unidad { get; set; }
    }
}
