//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato_Punto_Control
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato_Punto_Control()
        {
            this.Contrato_Ronda_Punto = new HashSet<Contrato_Ronda_Punto>();
        }
    
        public System.Guid IdContrato { get; set; }
        public System.Guid IdPunto { get; set; }
        public float Latitud { get; set; }
        public float Longitud { get; set; }
        public float Altitud { get; set; }
        public string IpDispositivo { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Ronda_Punto> Contrato_Ronda_Punto { get; set; }
    }
}
