//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato_Cartelera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato_Cartelera()
        {
            this.Contrato_Cartelera_Comentario = new HashSet<Contrato_Cartelera_Comentario>();
            this.Contrato_Cartelera_Imagen = new HashSet<Contrato_Cartelera_Imagen>();
        }
    
        public System.Guid IdContrato { get; set; }
        public System.Guid IdElemento { get; set; }
        public int IdTipoCartelera { get; set; }
        public System.Guid IdUnidad { get; set; }
        public System.DateTime FechaPublicacion { get; set; }
        public string Descripcion { get; set; }
        public System.Guid IdUsuario { get; set; }
        public string TituloMensaje { get; set; }
        public bool Publico { get; set; }
        public int VotosPositivos { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Cartelera_Comentario> Contrato_Cartelera_Comentario { get; set; }
        public virtual Contrato_Unidad Contrato_Unidad { get; set; }
        public virtual Contrato_Usuario Contrato_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Cartelera_Imagen> Contrato_Cartelera_Imagen { get; set; }
        public virtual TipoCartelera TipoCartelera { get; set; }
    }
}
