//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato_Administradora
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato_Administradora()
        {
            this.Contrato = new HashSet<Contrato>();
        }
    
        public int IdPais { get; set; }
        public System.Guid IdAdministradora { get; set; }
        public string Nombre { get; set; }
        public string Rif { get; set; }
        public string Direccion { get; set; }
        public int IdEstado { get; set; }
        public int IdCiudad { get; set; }
        public string CodigoPostal { get; set; }
        public string NombreContacto { get; set; }
        public string TelefonoOficina { get; set; }
        public string TelefonoCelular1 { get; set; }
        public string TelefonoCelular2 { get; set; }
        public string TelefonoFax { get; set; }
        public string CorreoElectronicoAdministradora { get; set; }
        public string CorreoElectronicoContacto { get; set; }
    
        public virtual Pais Pais { get; set; }
        public virtual Pais_Estado Pais_Estado { get; set; }
        public virtual Pais_Estado_Ciudad Pais_Estado_Ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contrato { get; set; }
    }
}
