//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato_Dispositivo_Bitacora
    {
        public System.Guid IdContrato { get; set; }
        public System.Guid IdDispositivo { get; set; }
        public System.DateTime FechaLog { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string LineaLog { get; set; }
    
        public virtual Contrato_Dispositivo Contrato_Dispositivo { get; set; }
        public virtual Contrato Contrato { get; set; }
    }
}
