//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato_Unidad_Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato_Unidad_Persona()
        {
            this.Contrato_Unidad_Persona_Acceso = new HashSet<Contrato_Unidad_Persona_Acceso>();
            this.Contrato_Unidad_Persona_Acceso_Horario = new HashSet<Contrato_Unidad_Persona_Acceso_Horario>();
            this.Contrato_Unidad_Persona_AlarmaSilente_Bitacora = new HashSet<Contrato_Unidad_Persona_AlarmaSilente_Bitacora>();
            this.Contrato_Unidad_Persona_AlarmaSilente = new HashSet<Contrato_Unidad_Persona_AlarmaSilente>();
            this.Contrato_Unidad_Persona_Biometria_Trasmision = new HashSet<Contrato_Unidad_Persona_Biometria_Trasmision>();
            this.Contrato_Unidad_Vehiculo = new HashSet<Contrato_Unidad_Vehiculo>();
            this.Ticket = new HashSet<Ticket>();
        }
    
        public System.Guid IdContrato { get; set; }
        public System.Guid IdUnidad { get; set; }
        public System.Guid IdPersona { get; set; }
        public int IdTipoPersona { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Cedula { get; set; }
        public string Email { get; set; }
        public string DireccionHabitacion { get; set; }
        public string DireccionOficina { get; set; }
        public string TelefonoHabitacion { get; set; }
        public string TelefonoOficina { get; set; }
        public string TelefonoCelular { get; set; }
        public byte[] Imagen { get; set; }
        public Nullable<System.Guid> IdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Unidad_Persona_Acceso> Contrato_Unidad_Persona_Acceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Unidad_Persona_Acceso_Horario> Contrato_Unidad_Persona_Acceso_Horario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Unidad_Persona_AlarmaSilente_Bitacora> Contrato_Unidad_Persona_AlarmaSilente_Bitacora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Unidad_Persona_AlarmaSilente> Contrato_Unidad_Persona_AlarmaSilente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Unidad_Persona_Biometria_Trasmision> Contrato_Unidad_Persona_Biometria_Trasmision { get; set; }
        public virtual Contrato_Usuario Contrato_Usuario { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Unidad_Vehiculo> Contrato_Unidad_Vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
        public virtual Contrato Contrato { get; set; }
        public virtual Contrato_Unidad Contrato_Unidad { get; set; }
    }
}
