//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato_RFID
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato_RFID()
        {
            this.Contrato_Unidad_Vehiculo = new HashSet<Contrato_Unidad_Vehiculo>();
        }
    
        public System.Guid IdContrato { get; set; }
        public System.Guid IdRFID { get; set; }
        public byte[] Codigo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public bool Visitante { get; set; }
        public bool Temporal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Unidad_Vehiculo> Contrato_Unidad_Vehiculo { get; set; }
        public virtual Contrato Contrato { get; set; }
    }
}
