//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato_Unidad_Vehiculo
    {
        public System.Guid IdContrato { get; set; }
        public System.Guid IdEstacionamiento { get; set; }
        public System.Guid IdUnidad { get; set; }
        public System.Guid IdPuesto { get; set; }
        public string CodigoPuesto { get; set; }
        public int IdTipoVehiculo { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string NroMatricula { get; set; }
        public System.Guid IdPersona { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<System.Guid> IdRFID { get; set; }
    
        public virtual Contrato_Estacionamiento Contrato_Estacionamiento { get; set; }
        public virtual Contrato_RFID Contrato_RFID { get; set; }
        public virtual Contrato_Unidad_Persona Contrato_Unidad_Persona { get; set; }
        public virtual Contrato Contrato { get; set; }
        public virtual Contrato_Unidad Contrato_Unidad { get; set; }
    }
}
