//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato_Dispositivo_Clonacion
    {
        public System.Guid IdContrato { get; set; }
        public System.Guid IdDispositivoActivo { get; set; }
        public System.Guid IdDispositivoClonado { get; set; }
        public System.DateTime FechaClonacion { get; set; }
        public System.DateTime FechaInstalacion { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual Contrato_Dispositivo Contrato_Dispositivo { get; set; }
        public virtual Contrato_Dispositivo Contrato_Dispositivo1 { get; set; }
    }
}
