//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato_Facturacion
    {
        public System.Guid IdContrato { get; set; }
        public System.Guid IdFactura { get; set; }
        public string NroFactura { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public int MesFacturado { get; set; }
        public int AñoFacturado { get; set; }
        public float MontoFactura { get; set; }
        public bool Pagado { get; set; }
    
        public virtual Contrato Contrato { get; set; }
    }
}
