//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public System.Guid IdContacto { get; set; }
        public string Nombre { get; set; }
        public string TelefonoLocal { get; set; }
        public string TelefonoMovil { get; set; }
        public string Email { get; set; }
        public string Residencia { get; set; }
        public int CantidadVivienda { get; set; }
        public string Urbanizacion { get; set; }
        public int IdPais { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> IdCiudad { get; set; }
        public string Comentario { get; set; }
    
        public virtual Pais Pais { get; set; }
        public virtual Pais_Estado Pais_Estado { get; set; }
        public virtual Pais_Estado_Ciudad Pais_Estado_Ciudad { get; set; }
    }
}
