//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato_Correos_Seguricel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato_Correos_Seguricel()
        {
            this.Contrato_Correos_Seguricel_Destinatarios = new HashSet<Contrato_Correos_Seguricel_Destinatarios>();
        }
    
        public System.Guid IdContrato { get; set; }
        public System.Guid IdUnidad { get; set; }
        public System.Guid IdCorreo { get; set; }
        public System.DateTime FechaRecepcion { get; set; }
        public System.DateTime FechaEnvio { get; set; }
        public string Remitente { get; set; }
        public string Asunto { get; set; }
        public byte[] Contenido { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual Contrato_Unidad Contrato_Unidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Correos_Seguricel_Destinatarios> Contrato_Correos_Seguricel_Destinatarios { get; set; }
    }
}
