//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato_TipoArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato_TipoArea()
        {
            this.Contrato_TipoArea_Evento = new HashSet<Contrato_TipoArea_Evento>();
        }
    
        public System.Guid IdContrato { get; set; }
        public long IdTipoArea { get; set; }
        public string Nombre { get; set; }
        public System.TimeSpan HorarioInicio1 { get; set; }
        public System.TimeSpan HorarioFin1 { get; set; }
        public float Monto_Alquiler_Interno { get; set; }
        public float Monto_Alquiler_Externo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_TipoArea_Evento> Contrato_TipoArea_Evento { get; set; }
    }
}
