//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato_Unidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato_Unidad()
        {
            this.Contrato_Cartelera = new HashSet<Contrato_Cartelera>();
            this.Contrato_Correos_Seguricel = new HashSet<Contrato_Correos_Seguricel>();
            this.Contrato_Correos_Seguricel_Destinatarios = new HashSet<Contrato_Correos_Seguricel_Destinatarios>();
            this.Contrato_JuntaCondominio = new HashSet<Contrato_JuntaCondominio>();
            this.Contrato_Mensaje = new HashSet<Contrato_Mensaje>();
            this.Contrato_Mensaje_Destinatario = new HashSet<Contrato_Mensaje_Destinatario>();
            this.Contrato_TipoArea_Evento = new HashSet<Contrato_TipoArea_Evento>();
            this.Contrato_Unidad_Anuncio = new HashSet<Contrato_Unidad_Anuncio>();
            this.Contrato_Unidad_Bloqueo_Acceso = new HashSet<Contrato_Unidad_Bloqueo_Acceso>();
            this.Contrato_Unidad_Factura = new HashSet<Contrato_Unidad_Factura>();
            this.Contrato_Unidad_Persona_Acceso = new HashSet<Contrato_Unidad_Persona_Acceso>();
            this.Contrato_Unidad_Persona_Acceso_Horario = new HashSet<Contrato_Unidad_Persona_Acceso_Horario>();
            this.Contrato_Unidad_Persona_AlarmaSilente_Bitacora = new HashSet<Contrato_Unidad_Persona_AlarmaSilente_Bitacora>();
            this.Contrato_Unidad_Persona_AlarmaSilente = new HashSet<Contrato_Unidad_Persona_AlarmaSilente>();
            this.Contrato_Unidad_Persona_Biometria_Trasmision = new HashSet<Contrato_Unidad_Persona_Biometria_Trasmision>();
            this.Contrato_Unidad_Persona = new HashSet<Contrato_Unidad_Persona>();
            this.Contrato_Unidad_Vehiculo = new HashSet<Contrato_Unidad_Vehiculo>();
            this.Contrato_Unidad_Visitas = new HashSet<Contrato_Unidad_Visitas>();
            this.Ticket = new HashSet<Ticket>();
        }
    
        public System.Guid IdContrato { get; set; }
        public System.Guid IdUnidad { get; set; }
        public string Nombre { get; set; }
        public string Torre { get; set; }
        public string Piso { get; set; }
        public string Identificacion { get; set; }
        public long CodigoIdentificacionVigilancia { get; set; }
        public int CodigoAutorizacionAcceso { get; set; }
        public bool ModoVacaciones { get; set; }
        public bool Activa { get; set; }
        public System.Guid IdUnidadMaestra { get; set; }
        public string NombrePrincipal { get; set; }
        public string CorreoElectronicoPrincipal { get; set; }
        public string Telefono { get; set; }
        public string Ubicacion { get; set; }
        public bool Seguridad { get; set; }
        public bool RetrasmisionSMS { get; set; }
        public int MaximoSecundarios { get; set; }
        public int MaximoInvitados { get; set; }
        public byte[] Image { get; set; }
        public bool AccesoVigilancia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Cartelera> Contrato_Cartelera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Correos_Seguricel> Contrato_Correos_Seguricel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Correos_Seguricel_Destinatarios> Contrato_Correos_Seguricel_Destinatarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_JuntaCondominio> Contrato_JuntaCondominio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Mensaje> Contrato_Mensaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Mensaje_Destinatario> Contrato_Mensaje_Destinatario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_TipoArea_Evento> Contrato_TipoArea_Evento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Unidad_Anuncio> Contrato_Unidad_Anuncio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Unidad_Bloqueo_Acceso> Contrato_Unidad_Bloqueo_Acceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Unidad_Factura> Contrato_Unidad_Factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Unidad_Persona_Acceso> Contrato_Unidad_Persona_Acceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Unidad_Persona_Acceso_Horario> Contrato_Unidad_Persona_Acceso_Horario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Unidad_Persona_AlarmaSilente_Bitacora> Contrato_Unidad_Persona_AlarmaSilente_Bitacora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Unidad_Persona_AlarmaSilente> Contrato_Unidad_Persona_AlarmaSilente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Unidad_Persona_Biometria_Trasmision> Contrato_Unidad_Persona_Biometria_Trasmision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Unidad_Persona> Contrato_Unidad_Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Unidad_Vehiculo> Contrato_Unidad_Vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Unidad_Visitas> Contrato_Unidad_Visitas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
