//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato_Unidad_Persona_AlarmaSilente_Bitacora
    {
        public System.Guid IdContrato { get; set; }
        public System.Guid IdUnidad { get; set; }
        public System.Guid IdPersona { get; set; }
        public System.Guid IdAlarmaSilente { get; set; }
        public System.Guid IdBitacora { get; set; }
        public string TelefonoEmisor { get; set; }
        public string TelefonoSMS { get; set; }
        public string MensajeSMS { get; set; }
        public bool Enviado { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaEnvio { get; set; }
        public System.DateTime FechaRecepcion { get; set; }
        public string NombreEmisor { get; set; }
        public string NombreReceptor { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual Contrato_Unidad Contrato_Unidad { get; set; }
        public virtual Contrato_Unidad_Persona Contrato_Unidad_Persona { get; set; }
        public virtual Contrato_Unidad_Persona_AlarmaSilente Contrato_Unidad_Persona_AlarmaSilente { get; set; }
    }
}
