//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato_Acceso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato_Acceso()
        {
            this.Contrato_Dispositivo = new HashSet<Contrato_Dispositivo>();
            this.Contrato_Dispositivo_Estadistica = new HashSet<Contrato_Dispositivo_Estadistica>();
            this.Contrato_Unidad_Bloqueo_Acceso = new HashSet<Contrato_Unidad_Bloqueo_Acceso>();
            this.Contrato_Unidad_Persona_Acceso = new HashSet<Contrato_Unidad_Persona_Acceso>();
            this.Contrato_Unidad_Persona_Biometria_Trasmision = new HashSet<Contrato_Unidad_Persona_Biometria_Trasmision>();
        }
    
        public System.Guid IdContrato { get; set; }
        public System.Guid IdAcceso { get; set; }
        public string Nombre { get; set; }
        public int NroPersonas { get; set; }
        public bool JuntaCondominio { get; set; }
        public int CantidadSecundarios { get; set; }
        public int Plantillas_X_Persona { get; set; }
        public int Plantillas_Emergencia { get; set; }
        public byte[] IdSubRed { get; set; }
        public bool Entrada { get; set; }
        public bool Salida { get; set; }
        public bool Personal { get; set; }
        public bool Peatonal { get; set; }
        public bool Vehicular { get; set; }
        public bool Servicio { get; set; }
        public bool RFID { get; set; }
        public bool Principales { get; set; }
        public bool Secundarios { get; set; }
        public bool Visitante { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Dispositivo> Contrato_Dispositivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Dispositivo_Estadistica> Contrato_Dispositivo_Estadistica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Unidad_Bloqueo_Acceso> Contrato_Unidad_Bloqueo_Acceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Unidad_Persona_Acceso> Contrato_Unidad_Persona_Acceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Unidad_Persona_Biometria_Trasmision> Contrato_Unidad_Persona_Biometria_Trasmision { get; set; }
    }
}
