//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato_TipoArea_Evento
    {
        public System.Guid IdContrato { get; set; }
        public long IdTipoArea { get; set; }
        public System.Guid IdEvento { get; set; }
        public Nullable<System.Guid> IdUnidad { get; set; }
        public string Motivo { get; set; }
        public System.DateTime FechaEvento { get; set; }
        public Nullable<System.Guid> IdUsuarioSolicitud { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public bool Aprobado { get; set; }
        public System.Guid IdUsuarioAprueba { get; set; }
        public System.DateTime FechaAprobado { get; set; }
        public bool SolicitudExterna { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual Contrato_TipoArea Contrato_TipoArea { get; set; }
        public virtual Contrato_Unidad Contrato_Unidad { get; set; }
        public virtual Contrato_Usuario Contrato_Usuario { get; set; }
        public virtual Contrato_Usuario Contrato_Usuario1 { get; set; }
    }
}
