//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cotizacion()
        {
            this.Cotizacion_Acceso = new HashSet<Cotizacion_Acceso>();
            this.Cotizacion_Contacto = new HashSet<Cotizacion_Contacto>();
            this.Cotizacion_Dispositivo = new HashSet<Cotizacion_Dispositivo>();
        }
    
        public System.Guid IdCotizacion { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public System.Guid IdVendedor { get; set; }
        public Nullable<System.Guid> IdContrato { get; set; }
        public int IdPais { get; set; }
        public int IdEstado { get; set; }
        public int IdCiudad { get; set; }
        public int IdTipoPropuesta { get; set; }
        public int IdEstadoPropuesta { get; set; }
        public System.DateTime FechaEstadoPropuesta { get; set; }
        public int TotalTorres { get; set; }
        public int NroResidenciasXTorre { get; set; }
        public int TotalResidencias { get; set; }
        public int NroLocalesComerciales { get; set; }
        public string DescripcionAccesoActual { get; set; }
        public bool AccesoTelefonico { get; set; }
        public bool AccesoBiometrico { get; set; }
        public bool AlarmaSilente { get; set; }
        public bool ControlVigilancia { get; set; }
        public bool AccesoRFID { get; set; }
        public Nullable<bool> VigilanciaContratada { get; set; }
        public string NombreEmpresaVigilancia { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cotizacion_Acceso> Cotizacion_Acceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cotizacion_Contacto> Cotizacion_Contacto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cotizacion_Dispositivo> Cotizacion_Dispositivo { get; set; }
        public virtual EstadoPropuesta EstadoPropuesta { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Pais_Estado Pais_Estado { get; set; }
        public virtual Pais_Estado_Ciudad Pais_Estado_Ciudad { get; set; }
        public virtual TipoPropuesta TipoPropuesta { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
