//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacion_Dispositivo
    {
        public System.Guid IdCotizacion { get; set; }
        public int IdTipoDispositivo { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual Cotizacion Cotizacion { get; set; }
    }
}
