//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacion_Parametros_Calculo
    {
        public System.DateTime FechaCotizacionParametros { get; set; }
        public float PorcentajeGanancia { get; set; }
        public float PorcentajeServicio { get; set; }
        public float PorcetajeArrendamiento { get; set; }
    }
}
