//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaCorreoSeguricel
    {
        public int IdCuentaCorreo { get; set; }
        public string DireccionEmail { get; set; }
        public string DireccionPOP { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public int Puerto { get; set; }
        public bool RequiereSSL { get; set; }
    }
}
