//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firmware
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Firmware()
        {
            this.Contrato_Dispositivo = new HashSet<Contrato_Dispositivo>();
        }
    
        public System.Guid IdFirmware { get; set; }
        public string Version { get; set; }
        public string Descripcion { get; set; }
        public byte[] Firmware1 { get; set; }
        public int IdTipoDispositivo { get; set; }
        public Nullable<System.DateTime> FechaPubilcacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Dispositivo> Contrato_Dispositivo { get; set; }
    }
}
