//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Visitas
    {
        public System.Guid IdVisita { get; set; }
        public string DireccionIP { get; set; }
        public string ServidorRemoto { get; set; }
        public int CantidadVisitas { get; set; }
    }
}
