//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Modulo()
        {
            this.Modulo1 = new HashSet<Modulo>();
            this.Modulo_TipoUsuario = new HashSet<Modulo_TipoUsuario>();
            this.Usuario_Bitacora = new HashSet<Usuario_Bitacora>();
        }
    
        public long IdModulo { get; set; }
        public Nullable<long> IdModuloPadre { get; set; }
        public int IdTipoElemento { get; set; }
        public string Nombre { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Modulo> Modulo1 { get; set; }
        public virtual Modulo Modulo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Modulo_TipoUsuario> Modulo_TipoUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Bitacora> Usuario_Bitacora { get; set; }
    }
}
