//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operadora_Contacto
    {
        public int IdPais { get; set; }
        public System.Guid IdOperadora { get; set; }
        public System.Guid IdContacto { get; set; }
        public int IdTipoContacto { get; set; }
        public string Nombre { get; set; }
        public string TelefonoOficina { get; set; }
        public string TelefonoMovil { get; set; }
    
        public virtual Operadora Operadora { get; set; }
    }
}
