//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pais
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pais()
        {
            this.Contacto = new HashSet<Contacto>();
            this.Contrato_Administradora = new HashSet<Contrato_Administradora>();
            this.Cotizacion = new HashSet<Cotizacion>();
            this.Franquicia = new HashSet<Franquicia>();
            this.MonedaExtranjera_TasaCambio = new HashSet<MonedaExtranjera_TasaCambio>();
            this.TipoCargoJuntaCondominio = new HashSet<TipoCargoJuntaCondominio>();
            this.Pais_Estado_Ciudad = new HashSet<Pais_Estado_Ciudad>();
            this.Pais_Estado = new HashSet<Pais_Estado>();
            this.Contrato = new HashSet<Contrato>();
        }
    
        public int IdPais { get; set; }
        public string Nombre { get; set; }
        public int IdMonedaOficial { get; set; }
        public bool Activo { get; set; }
        public string Culture { get; set; }
        public System.Data.Entity.Spatial.DbGeography Ubicacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacto> Contacto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Administradora> Contrato_Administradora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cotizacion> Cotizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Franquicia> Franquicia { get; set; }
        public virtual MonedaExtranjera MonedaExtranjera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonedaExtranjera_TasaCambio> MonedaExtranjera_TasaCambio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoCargoJuntaCondominio> TipoCargoJuntaCondominio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pais_Estado_Ciudad> Pais_Estado_Ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pais_Estado> Pais_Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contrato { get; set; }
    }
}
