//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeguricelEntities : DbContext
    {
        public SeguricelEntities()
            : base("name=SeguricelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contacto> Contacto { get; set; }
        public virtual DbSet<Contrato> Contrato { get; set; }
        public virtual DbSet<Contrato_Acceso> Contrato_Acceso { get; set; }
        public virtual DbSet<Contrato_Administradora> Contrato_Administradora { get; set; }
        public virtual DbSet<Contrato_Cartelera> Contrato_Cartelera { get; set; }
        public virtual DbSet<Contrato_Cartelera_Comentario> Contrato_Cartelera_Comentario { get; set; }
        public virtual DbSet<Contrato_Cartelera_Imagen> Contrato_Cartelera_Imagen { get; set; }
        public virtual DbSet<Contrato_Contacto> Contrato_Contacto { get; set; }
        public virtual DbSet<Contrato_Correos_Seguricel> Contrato_Correos_Seguricel { get; set; }
        public virtual DbSet<Contrato_Correos_Seguricel_Destinatarios> Contrato_Correos_Seguricel_Destinatarios { get; set; }
        public virtual DbSet<Contrato_Dispositivo> Contrato_Dispositivo { get; set; }
        public virtual DbSet<Contrato_Dispositivo_Actualizacion> Contrato_Dispositivo_Actualizacion { get; set; }
        public virtual DbSet<Contrato_Dispositivo_Bitacora> Contrato_Dispositivo_Bitacora { get; set; }
        public virtual DbSet<Contrato_Dispositivo_Clonacion> Contrato_Dispositivo_Clonacion { get; set; }
        public virtual DbSet<Contrato_Dispositivo_Estadistica> Contrato_Dispositivo_Estadistica { get; set; }
        public virtual DbSet<Contrato_Estacionamiento> Contrato_Estacionamiento { get; set; }
        public virtual DbSet<Contrato_Facturacion> Contrato_Facturacion { get; set; }
        public virtual DbSet<Contrato_JuntaCondominio> Contrato_JuntaCondominio { get; set; }
        public virtual DbSet<Contrato_Mensaje> Contrato_Mensaje { get; set; }
        public virtual DbSet<Contrato_Mensaje_Anexo> Contrato_Mensaje_Anexo { get; set; }
        public virtual DbSet<Contrato_Mensaje_Destinatario> Contrato_Mensaje_Destinatario { get; set; }
        public virtual DbSet<Contrato_Publicacion> Contrato_Publicacion { get; set; }
        public virtual DbSet<Contrato_Punto_Control> Contrato_Punto_Control { get; set; }
        public virtual DbSet<Contrato_RFID> Contrato_RFID { get; set; }
        public virtual DbSet<Contrato_Ronda> Contrato_Ronda { get; set; }
        public virtual DbSet<Contrato_Ronda_Punto> Contrato_Ronda_Punto { get; set; }
        public virtual DbSet<Contrato_TipoArea> Contrato_TipoArea { get; set; }
        public virtual DbSet<Contrato_TipoArea_Evento> Contrato_TipoArea_Evento { get; set; }
        public virtual DbSet<Contrato_Unidad> Contrato_Unidad { get; set; }
        public virtual DbSet<Contrato_Unidad_Anuncio> Contrato_Unidad_Anuncio { get; set; }
        public virtual DbSet<Contrato_Unidad_Bloqueo_Acceso> Contrato_Unidad_Bloqueo_Acceso { get; set; }
        public virtual DbSet<Contrato_Unidad_Factura> Contrato_Unidad_Factura { get; set; }
        public virtual DbSet<Contrato_Unidad_Persona> Contrato_Unidad_Persona { get; set; }
        public virtual DbSet<Contrato_Unidad_Persona_Acceso> Contrato_Unidad_Persona_Acceso { get; set; }
        public virtual DbSet<Contrato_Unidad_Persona_Acceso_Horario> Contrato_Unidad_Persona_Acceso_Horario { get; set; }
        public virtual DbSet<Contrato_Unidad_Persona_AlarmaSilente> Contrato_Unidad_Persona_AlarmaSilente { get; set; }
        public virtual DbSet<Contrato_Unidad_Persona_AlarmaSilente_Bitacora> Contrato_Unidad_Persona_AlarmaSilente_Bitacora { get; set; }
        public virtual DbSet<Contrato_Unidad_Persona_Biometria> Contrato_Unidad_Persona_Biometria { get; set; }
        public virtual DbSet<Contrato_Unidad_Persona_Biometria_Trasmision> Contrato_Unidad_Persona_Biometria_Trasmision { get; set; }
        public virtual DbSet<Contrato_Unidad_Vehiculo> Contrato_Unidad_Vehiculo { get; set; }
        public virtual DbSet<Contrato_Unidad_Visitas> Contrato_Unidad_Visitas { get; set; }
        public virtual DbSet<Contrato_Usuario> Contrato_Usuario { get; set; }
        public virtual DbSet<Contrato_Usuario_Config_Cartelera> Contrato_Usuario_Config_Cartelera { get; set; }
        public virtual DbSet<Cotizacion> Cotizacion { get; set; }
        public virtual DbSet<Cotizacion_Acceso> Cotizacion_Acceso { get; set; }
        public virtual DbSet<Cotizacion_Contacto> Cotizacion_Contacto { get; set; }
        public virtual DbSet<Cotizacion_Dispositivo> Cotizacion_Dispositivo { get; set; }
        public virtual DbSet<Cotizacion_Parametros_Calculo> Cotizacion_Parametros_Calculo { get; set; }
        public virtual DbSet<CuentaCorreoSeguricel> CuentaCorreoSeguricel { get; set; }
        public virtual DbSet<EstadoContrato> EstadoContrato { get; set; }
        public virtual DbSet<EstadoPropuesta> EstadoPropuesta { get; set; }
        public virtual DbSet<EstadoPublicacion> EstadoPublicacion { get; set; }
        public virtual DbSet<EstadoTicket> EstadoTicket { get; set; }
        public virtual DbSet<EstadoUsuario> EstadoUsuario { get; set; }
        public virtual DbSet<EstadoVenta> EstadoVenta { get; set; }
        public virtual DbSet<Firmware> Firmware { get; set; }
        public virtual DbSet<Franquicia> Franquicia { get; set; }
        public virtual DbSet<Franquicia_Contacto> Franquicia_Contacto { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<Log_Visitas> Log_Visitas { get; set; }
        public virtual DbSet<Modulo> Modulo { get; set; }
        public virtual DbSet<Modulo_TipoUsuario> Modulo_TipoUsuario { get; set; }
        public virtual DbSet<MonedaExtranjera> MonedaExtranjera { get; set; }
        public virtual DbSet<MonedaExtranjera_TasaCambio> MonedaExtranjera_TasaCambio { get; set; }
        public virtual DbSet<Operadora> Operadora { get; set; }
        public virtual DbSet<Operadora_Contacto> Operadora_Contacto { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Pais_Estado> Pais_Estado { get; set; }
        public virtual DbSet<Pais_Estado_Ciudad> Pais_Estado_Ciudad { get; set; }
        public virtual DbSet<SubGrupo> SubGrupo { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<TicketSeguimiento> TicketSeguimiento { get; set; }
        public virtual DbSet<TipoAccion> TipoAccion { get; set; }
        public virtual DbSet<TipoAnuncio> TipoAnuncio { get; set; }
        public virtual DbSet<TipoBandeja> TipoBandeja { get; set; }
        public virtual DbSet<TipoCargoJuntaCondominio> TipoCargoJuntaCondominio { get; set; }
        public virtual DbSet<TipoCartelera> TipoCartelera { get; set; }
        public virtual DbSet<TipoContacto> TipoContacto { get; set; }
        public virtual DbSet<TipoContrato> TipoContrato { get; set; }
        public virtual DbSet<TipoDispositivo> TipoDispositivo { get; set; }
        public virtual DbSet<TipoDispositivo_Comando_Sincronizador> TipoDispositivo_Comando_Sincronizador { get; set; }
        public virtual DbSet<TipoMensaje> TipoMensaje { get; set; }
        public virtual DbSet<TipoPersona> TipoPersona { get; set; }
        public virtual DbSet<TipoPropuesta> TipoPropuesta { get; set; }
        public virtual DbSet<TipoTicket> TipoTicket { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<TipoVehiculo> TipoVehiculo { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Usuario_Bitacora> Usuario_Bitacora { get; set; }
        public virtual DbSet<Usuario_Perfil> Usuario_Perfil { get; set; }
        public virtual DbSet<Vendedor> Vendedor { get; set; }
        public virtual DbSet<Vendedor_Movimiento> Vendedor_Movimiento { get; set; }
    }
}
