//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubGrupo
    {
        public string Cuture { get; set; }
        public System.Guid IdGrupo { get; set; }
        public System.Guid IdSubGrupo { get; set; }
        public string Nombre { get; set; }
        public string Codigo { get; set; }
    
        public virtual Grupo Grupo { get; set; }
    }
}
