//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguricel3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.Ticket1 = new HashSet<Ticket>();
            this.TicketSeguimiento = new HashSet<TicketSeguimiento>();
        }
    
        public System.Guid IdTicket { get; set; }
        public System.Guid IdContrato { get; set; }
        public System.Guid IdUnidad { get; set; }
        public int IdTipoTicket { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaReporte { get; set; }
        public System.Guid IdPersonaReporta { get; set; }
        public string NombrePersonaReporta { get; set; }
        public System.Guid IdTicketPadre { get; set; }
        public System.Guid IdUsuarioRegistra { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual Contrato_Unidad Contrato_Unidad { get; set; }
        public virtual Contrato_Unidad_Persona Contrato_Unidad_Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket1 { get; set; }
        public virtual Ticket Ticket2 { get; set; }
        public virtual TipoTicket TipoTicket { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketSeguimiento> TicketSeguimiento { get; set; }
    }
}
