//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdministradorasResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdministradorasResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Seguricel3.App_GlobalResources.Administracion.Administradoras.AdministradorasReso" +
                            "urces", typeof(AdministradorasResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Administradora.
        /// </summary>
        public static string CreateHeaderPage {
            get {
                return ResourceManager.GetString("CreateHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Nuevo Administradora.
        /// </summary>
        public static string CreatePageTitle {
            get {
                return ResourceManager.GetString("CreatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Administradora.
        /// </summary>
        public static string EditHeaderPage {
            get {
                return ResourceManager.GetString("EditHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Actualizar Administradora.
        /// </summary>
        public static string EditPageTitle {
            get {
                return ResourceManager.GetString("EditPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimiento de Administradoras.
        /// </summary>
        public static string HeaderPage {
            get {
                return ResourceManager.GetString("HeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        public static string labelCiudad {
            get {
                return ResourceManager.GetString("labelCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Postal.
        /// </summary>
        public static string labelCodigoPostal {
            get {
                return ResourceManager.GetString("labelCodigoPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string labelDireccion {
            get {
                return ResourceManager.GetString("labelDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico Corporativo.
        /// </summary>
        public static string labelEmailAdministradora {
            get {
                return ResourceManager.GetString("labelEmailAdministradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico Contacto.
        /// </summary>
        public static string labelEmailContacto {
            get {
                return ResourceManager.GetString("labelEmailContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string labelEstado {
            get {
                return ResourceManager.GetString("labelEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string labelNombre {
            get {
                return ResourceManager.GetString("labelNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        public static string labelNombreContacto {
            get {
                return ResourceManager.GetString("labelNombreContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        public static string labelPais {
            get {
                return ResourceManager.GetString("labelPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro Fiscal.
        /// </summary>
        public static string labelRIF {
            get {
                return ResourceManager.GetString("labelRIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono Celular Principal.
        /// </summary>
        public static string labelTelefonoCelular {
            get {
                return ResourceManager.GetString("labelTelefonoCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono Celular Secundario.
        /// </summary>
        public static string labelTelefonoCelular2 {
            get {
                return ResourceManager.GetString("labelTelefonoCelular2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono Fax.
        /// </summary>
        public static string labelTelefonoFax {
            get {
                return ResourceManager.GetString("labelTelefonoFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono Oficina.
        /// </summary>
        public static string labelTelefonoOficina {
            get {
                return ResourceManager.GetString("labelTelefonoOficina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Mantenimiento de Administradoras.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
    }
}
