//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HomeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.HomeResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Technology for comfort and security access control, vigilance and community.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attention.
        /// </summary>
        internal static string AtencionLinea1 {
            get {
                return ResourceManager.GetString("AtencionLinea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The whole community.
        /// </summary>
        internal static string AtencionLinea2 {
            get {
                return ResourceManager.GetString("AtencionLinea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a involves safety.
        /// </summary>
        internal static string AtencionLinea3 {
            get {
                return ResourceManager.GetString("AtencionLinea3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a and they are more careful..
        /// </summary>
        internal static string AtencionLinea4 {
            get {
                return ResourceManager.GetString("AtencionLinea4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company.
        /// </summary>
        internal static string CompanyLink {
            get {
                return ResourceManager.GetString("CompanyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact.
        /// </summary>
        internal static string ContactoLink {
            get {
                return ResourceManager.GetString("ContactoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We were waiting.
        /// </summary>
        internal static string ContentLine1 {
            get {
                return ResourceManager.GetString("ContentLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It is the most comprehensive preventive system for residential, attacking.
        /// </summary>
        internal static string ContentLine2 {
            get {
                return ResourceManager.GetString("ContentLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a vulnerabilities of communities to cover.
        /// </summary>
        internal static string ContentLine3_1 {
            get {
                return ResourceManager.GetString("ContentLine3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a three pillars of security..
        /// </summary>
        internal static string ContentLine3_2 {
            get {
                return ResourceManager.GetString("ContentLine3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a And all this based on the daily use of mobile and Internet.
        /// </summary>
        internal static string ContentLine4 {
            get {
                return ResourceManager.GetString("ContentLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Safety, comfort and control for your home and family.
        /// </summary>
        internal static string ContentLine5 {
            get {
                return ResourceManager.GetString("ContentLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Singularity.
        /// </summary>
        internal static string ContentLine6 {
            get {
                return ResourceManager.GetString("ContentLine6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A single system, product development and integration of technologies.
        /// </summary>
        internal static string ContentLine7 {
            get {
                return ResourceManager.GetString("ContentLine7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a electronics, telecommunications and the Internet, which seeks tranquility in.
        /// </summary>
        internal static string ContentLine8 {
            get {
                return ResourceManager.GetString("ContentLine8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a people with security in their homes..
        /// </summary>
        internal static string ContentLine9 {
            get {
                return ResourceManager.GetString("ContentLine9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access control.
        /// </summary>
        internal static string ControlAccesoLinea1 {
            get {
                return ResourceManager.GetString("ControlAccesoLinea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only members of the.
        /// </summary>
        internal static string ControlAccesoLinea2 {
            get {
                return ResourceManager.GetString("ControlAccesoLinea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a community open.
        /// </summary>
        internal static string ControlAccesoLinea3 {
            get {
                return ResourceManager.GetString("ControlAccesoLinea3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a the doors..
        /// </summary>
        internal static string ControlAccesoLinea4 {
            get {
                return ResourceManager.GetString("ControlAccesoLinea4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All rights reserved.
        /// </summary>
        internal static string FooterCopyright1 {
            get {
                return ResourceManager.GetString("FooterCopyright1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel 2015.
        /// </summary>
        internal static string FooterCopyright2 {
            get {
                return ResourceManager.GetString("FooterCopyright2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interconnected digital protection.
        /// </summary>
        internal static string FooterLinea1 {
            get {
                return ResourceManager.GetString("FooterLinea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The evolution of your safety!.
        /// </summary>
        internal static string FooterLinea2 {
            get {
                return ResourceManager.GetString("FooterLinea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See &quot;The solution&quot;.
        /// </summary>
        internal static string FooterLink1 {
            get {
                return ResourceManager.GetString("FooterLink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        internal static string HomeLink {
            get {
                return ResourceManager.GetString("HomeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users.
        /// </summary>
        internal static string LoginHeader {
            get {
                return ResourceManager.GetString("LoginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        internal static string LoginLink {
            get {
                return ResourceManager.GetString("LoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ask for information.
        /// </summary>
        internal static string PageHeaderContactLink {
            get {
                return ResourceManager.GetString("PageHeaderContactLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Feel safe.
        /// </summary>
        internal static string PageHeaderLine1 {
            get {
                return ResourceManager.GetString("PageHeaderLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a at home.
        /// </summary>
        internal static string PageHeaderLine2 {
            get {
                return ResourceManager.GetString("PageHeaderLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shielding your residential complex.
        /// </summary>
        internal static string PageHeaderLine3 {
            get {
                return ResourceManager.GetString("PageHeaderLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a with the most comprehensive and innovative.
        /// </summary>
        internal static string PageHeaderLine4 {
            get {
                return ResourceManager.GetString("PageHeaderLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a preventive security system.
        /// </summary>
        internal static string PageHeaderLine5 {
            get {
                return ResourceManager.GetString("PageHeaderLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a See video.
        /// </summary>
        internal static string PageHeaderVideo {
            get {
                return ResourceManager.GetString("PageHeaderVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Participation.
        /// </summary>
        internal static string ParticipacionLinea1 {
            get {
                return ResourceManager.GetString("ParticipacionLinea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The community.
        /// </summary>
        internal static string ParticipacionLinea2 {
            get {
                return ResourceManager.GetString("ParticipacionLinea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a communicate and participate.
        /// </summary>
        internal static string ParticipacionLinea3 {
            get {
                return ResourceManager.GetString("ParticipacionLinea3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a using comfortable.
        /// </summary>
        internal static string ParticipacionLinea4 {
            get {
                return ResourceManager.GetString("ParticipacionLinea4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tools..
        /// </summary>
        internal static string ParticipacionLinea5 {
            get {
                return ResourceManager.GetString("ParticipacionLinea5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Processing Requirement. Please wait....
        /// </summary>
        internal static string ProgressBarText {
            get {
                return ResourceManager.GetString("ProgressBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registration.
        /// </summary>
        internal static string RegistroLinea1 {
            get {
                return ResourceManager.GetString("RegistroLinea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It is documented all.
        /// </summary>
        internal static string RegistroLinea2 {
            get {
                return ResourceManager.GetString("RegistroLinea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a activity, eliminating.
        /// </summary>
        internal static string RegistroLinea3 {
            get {
                return ResourceManager.GetString("RegistroLinea3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a anonymity..
        /// </summary>
        internal static string RegistroLinea4 {
            get {
                return ResourceManager.GetString("RegistroLinea4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The solution.
        /// </summary>
        internal static string SolucionLink {
            get {
                return ResourceManager.GetString("SolucionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a watchers.
        /// </summary>
        internal static string VIgilantesLinea1 {
            get {
                return ResourceManager.GetString("VIgilantesLinea1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Optimizes use.
        /// </summary>
        internal static string VigilantesLinea2 {
            get {
                return ResourceManager.GetString("VigilantesLinea2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a vigilant and not fall asleep.
        /// </summary>
        internal static string VigilantesLinea3 {
            get {
                return ResourceManager.GetString("VigilantesLinea3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a and they do their work..
        /// </summary>
        internal static string VigilantesLinea4 {
            get {
                return ResourceManager.GetString("VigilantesLinea4", resourceCulture);
            }
        }
    }
}
