//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PerfilResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PerfilResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Seguricel3.App_GlobalResources.Account.Perfil.PerfilResource", typeof(PerfilResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Personales.
        /// </summary>
        public static string HeaderDatosPersonales {
            get {
                return ResourceManager.GetString("HeaderDatosPersonales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil del Usuario.
        /// </summary>
        public static string HeaderPage {
            get {
                return ResourceManager.GetString("HeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de Seguridad y Acceso.
        /// </summary>
        public static string HeaderSeguridad {
            get {
                return ResourceManager.GetString("HeaderSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apodo.
        /// </summary>
        public static string LabelApodo {
            get {
                return ResourceManager.GetString("LabelApodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string LabelConfirmarContraseña {
            get {
                return ResourceManager.GetString("LabelConfirmarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Nacimiento.
        /// </summary>
        public static string LabelFechaNacimiento {
            get {
                return ResourceManager.GetString("LabelFechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string LabelGuardar {
            get {
                return ResourceManager.GetString("LabelGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Femenino.
        /// </summary>
        public static string LabelHembra {
            get {
                return ResourceManager.GetString("LabelHembra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres y Apellidos.
        /// </summary>
        public static string LabelNombre {
            get {
                return ResourceManager.GetString("LabelNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primera pregunta de seguridad.
        /// </summary>
        public static string LabelPeguntaSeguridad1 {
            get {
                return ResourceManager.GetString("LabelPeguntaSeguridad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segunda pregunta de seguridad.
        /// </summary>
        public static string LabelPeguntaSeguridad2 {
            get {
                return ResourceManager.GetString("LabelPeguntaSeguridad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tercera pregunta de seguridad.
        /// </summary>
        public static string LabelPeguntaSeguridad3 {
            get {
                return ResourceManager.GetString("LabelPeguntaSeguridad3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Respuesta a la primera pregunta de seguridad.
        /// </summary>
        public static string LabelRespuestaSeguridad1 {
            get {
                return ResourceManager.GetString("LabelRespuestaSeguridad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Respuesta a la segunda pregunta de seguridad.
        /// </summary>
        public static string LabelRespuestaSeguridad2 {
            get {
                return ResourceManager.GetString("LabelRespuestaSeguridad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Respuesta a la tercera pregunta de seguridad.
        /// </summary>
        public static string LabelRespuestaSeguridad3 {
            get {
                return ResourceManager.GetString("LabelRespuestaSeguridad3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. de Teléfono.
        /// </summary>
        public static string LabelTelefono {
            get {
                return ResourceManager.GetString("LabelTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Masculino.
        /// </summary>
        public static string LabelVaron {
            get {
                return ResourceManager.GetString("LabelVaron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Perfil del Usuario.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
    }
}
