//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContactoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactoResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Seguricel3.App_GlobalResources.Home.Contacto.ContactoResource", typeof(ContactoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string BotonEnviarLabel {
            get {
                return ResourceManager.GetString("BotonEnviarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        public static string CiudadLabel {
            get {
                return ResourceManager.GetString("CiudadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una ciudad de la lista.
        /// </summary>
        public static string CiudadRangeErrorMessage {
            get {
                return ResourceManager.GetString("CiudadRangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe indicar la ciudad de la residencia.
        /// </summary>
        public static string CiudadRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CiudadRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentarios: Háblanos de tu conjunto residencial.
        /// </summary>
        public static string ComentarioLabel {
            get {
                return ResourceManager.GetString("ComentarioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de contacto.
        /// </summary>
        public static string ContactoHeader {
            get {
                return ResourceManager.GetString("ContactoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contáctanos.
        /// </summary>
        public static string ContactosTitulo {
            get {
                return ResourceManager.GetString("ContactosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string DireccionEspañaContenido {
            get {
                return ResourceManager.GetString("DireccionEspañaContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección de atención en Madrid - España.
        /// </summary>
        public static string DireccionEspañaTitulo {
            get {
                return ResourceManager.GetString("DireccionEspañaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string DireccionMiamiContenido {
            get {
                return ResourceManager.GetString("DireccionMiamiContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección de atención en Estados Unidos - Miami.
        /// </summary>
        public static string DireccionMiamiTitulo {
            get {
                return ResourceManager.GetString("DireccionMiamiTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string DireccionVenezuelaContenido {
            get {
                return ResourceManager.GetString("DireccionVenezuelaContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección de atención en Caracas - Venezuela.
        /// </summary>
        public static string DireccionVenezuelaTitulo {
            get {
                return ResourceManager.GetString("DireccionVenezuelaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico no es válido.
        /// </summary>
        public static string EmailContactoEmailErrorMessage {
            get {
                return ResourceManager.GetString("EmailContactoEmailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico.
        /// </summary>
        public static string EmailContactoLabel {
            get {
                return ResourceManager.GetString("EmailContactoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe indicar un correo electrónico de contacto.
        /// </summary>
        public static string EmailContactoRequieredErrorMessage {
            get {
                return ResourceManager.GetString("EmailContactoRequieredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico no debe exceder de 500 caracteres.
        /// </summary>
        public static string EmailContactoStringLengthErrorMessage {
            get {
                return ResourceManager.GetString("EmailContactoStringLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string EstadoLabel {
            get {
                return ResourceManager.GetString("EstadoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un estado de la lista.
        /// </summary>
        public static string EstadoRangeErrorMessage {
            get {
                return ResourceManager.GetString("EstadoRangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe indicar el estado de la residencia.
        /// </summary>
        public static string EstadoRequiredErrorMessage {
            get {
                return ResourceManager.GetString("EstadoRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string NombreContactoLabel {
            get {
                return ResourceManager.GetString("NombreContactoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe indicar el nombre de la persona contacto.
        /// </summary>
        public static string NombreContactoRequiredErrorMessage {
            get {
                return ResourceManager.GetString("NombreContactoRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conjunto Residencial.
        /// </summary>
        public static string NombreResidenciaLabel {
            get {
                return ResourceManager.GetString("NombreResidenciaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe indicar el nombre del conjunto residencial.
        /// </summary>
        public static string NombreResidenciaRequiredErrorMessage {
            get {
                return ResourceManager.GetString("NombreResidenciaRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre del conjunto residencial no debe exceder los 500 caracteres..
        /// </summary>
        public static string NombreResidenciaStringLengthErrorMessage {
            get {
                return ResourceManager.GetString("NombreResidenciaStringLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre del contacto no debe exceder los 500 caracteres.
        /// </summary>
        public static string NombreStringLengthErrorMessage {
            get {
                return ResourceManager.GetString("NombreStringLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Urbanización.
        /// </summary>
        public static string NombreUrbanizacionLabel {
            get {
                return ResourceManager.GetString("NombreUrbanizacionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe indicar el nombre de la urbanización.
        /// </summary>
        public static string NombreUrbanizacionRequiredErrorMessage {
            get {
                return ResourceManager.GetString("NombreUrbanizacionRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de la urbanización no debe exceder los 500 caracteres.
        /// </summary>
        public static string NombreUrbanizacionStringLengthErrorMessage {
            get {
                return ResourceManager.GetString("NombreUrbanizacionStringLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de viviendas.
        /// </summary>
        public static string NroViviendasLabel {
            get {
                return ResourceManager.GetString("NroViviendasLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de viviendas debe estar entre 1 y 9999.
        /// </summary>
        public static string NroViviendasRangeErrorMessage {
            get {
                return ResourceManager.GetString("NroViviendasRangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe indicar el numero de viviendas en el conjunto residencial.
        /// </summary>
        public static string NroViviendasRequiredErrorMessage {
            get {
                return ResourceManager.GetString("NroViviendasRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Como se enteró de nosotros?.
        /// </summary>
        public static string OpcionEnterarLabel {
            get {
                return ResourceManager.GetString("OpcionEnterarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búsqueda en Internet.
        /// </summary>
        public static string OpcionEnterarOpcion1 {
            get {
                return ResourceManager.GetString("OpcionEnterarOpcion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prensa.
        /// </summary>
        public static string OpcionEnterarOpcion2 {
            get {
                return ResourceManager.GetString("OpcionEnterarOpcion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Radio.
        /// </summary>
        public static string OpcionEnterarOpcion3 {
            get {
                return ResourceManager.GetString("OpcionEnterarOpcion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Redes Sociales.
        /// </summary>
        public static string OpcionEnterarOpcion4 {
            get {
                return ResourceManager.GetString("OpcionEnterarOpcion4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referido por otra persona.
        /// </summary>
        public static string OpcionEnterarOpcion5 {
            get {
                return ResourceManager.GetString("OpcionEnterarOpcion5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volante Publicitario.
        /// </summary>
        public static string OpcionEnterarOpcion6 {
            get {
                return ResourceManager.GetString("OpcionEnterarOpcion6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wayra.
        /// </summary>
        public static string OpcionEnterarOpcion7 {
            get {
                return ResourceManager.GetString("OpcionEnterarOpcion7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una opción.
        /// </summary>
        public static string OpcionEnterarRangeErrorMessage {
            get {
                return ResourceManager.GetString("OpcionEnterarRangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una opción.
        /// </summary>
        public static string OpcionEnterarRequiredErrorMessage {
            get {
                return ResourceManager.GetString("OpcionEnterarRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una opción.
        /// </summary>
        public static string OpcionEnterarSelectValue {
            get {
                return ResourceManager.GetString("OpcionEnterarSelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        public static string PaisLabel {
            get {
                return ResourceManager.GetString("PaisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un país de la lista.
        /// </summary>
        public static string PaisRangeErrorMessage {
            get {
                return ResourceManager.GetString("PaisRangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe indicar el país de la residencia.
        /// </summary>
        public static string PaisRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PaisRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se recibieron los parámetros correctamente.
        /// </summary>
        public static string ParameterExceptionMessage1 {
            get {
                return ResourceManager.GetString("ParameterExceptionMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información del conjunto residencial.
        /// </summary>
        public static string ResidenciaHeader {
            get {
                return ResourceManager.GetString("ResidenciaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperamos poder servirte.
        /// </summary>
        public static string SubtituloPagina {
            get {
                return ResourceManager.GetString("SubtituloPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tlf. Local.
        /// </summary>
        public static string TelefonoLocalContactoLabel {
            get {
                return ResourceManager.GetString("TelefonoLocalContactoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de teléfono local no es válido.
        /// </summary>
        public static string TelefonoLocalPhoneErrorMessage {
            get {
                return ResourceManager.GetString("TelefonoLocalPhoneErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de teléfono local debe tener como mínimo 10 dígitos.
        /// </summary>
        public static string TelefonoLocalStringLengthErrorMessage {
            get {
                return ResourceManager.GetString("TelefonoLocalStringLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tlf. Móvil.
        /// </summary>
        public static string TelefonoMovilContactoLabel {
            get {
                return ResourceManager.GetString("TelefonoMovilContactoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de teléfono móvil no es válido.
        /// </summary>
        public static string TelefonoMovilPhoneErrorMessage {
            get {
                return ResourceManager.GetString("TelefonoMovilPhoneErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe indicar un número de teléfono móvil.
        /// </summary>
        public static string TelefonoMovilRequieredErrorMessage {
            get {
                return ResourceManager.GetString("TelefonoMovilRequieredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de teléfono móvil debe tener como mínimo 10 dígitos.
        /// </summary>
        public static string TelefonoMovilStringLengthErrorMessage {
            get {
                return ResourceManager.GetString("TelefonoMovilStringLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        public static string TituloPagina {
            get {
                return ResourceManager.GetString("TituloPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor verifique los mensajes de error en la página.
        /// </summary>
        public static string ValidationSummaryMessage {
            get {
                return ResourceManager.GetString("ValidationSummaryMessage", resourceCulture);
            }
        }
    }
}
