//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CompanyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompanyResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CompanyResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Franquicia.
        /// </summary>
        internal static string ButtonFranquiciaTexto {
            get {
                return ResourceManager.GetString("ButtonFranquiciaTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equipo.
        /// </summary>
        internal static string EquipoHeader {
            get {
                return ResourceManager.GetString("EquipoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Somos un grupo de empresarios venezolanos con trayectoria en desarrollo de proyectos, donde contamos con profesionales con amplia experiencia en diseño industrial, electrónica, informática y telecomunicaciones, pero además contamos con el apoyo de genios en Mercadeo y Planificación financiera..
        /// </summary>
        internal static string EquipoParrafo1 {
            get {
                return ResourceManager.GetString("EquipoParrafo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cada miembro del equipo que lidera Seguricel tiene tiene amplia experiencia en su área, alta motivación, compromiso y confianza en el proyecto; pero contamos también con el networking y apuntalamiento de la estructura de Telefónica..
        /// </summary>
        internal static string EquipoParrafo2 {
            get {
                return ResourceManager.GetString("EquipoParrafo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detrás del equipo líder hay un grupo importante de ingenieros, técnicos y asesores, que ha intervenido en el desarrollo y hacen posible el día a día de Seguricel..
        /// </summary>
        internal static string EquipoParrafo3 {
            get {
                return ResourceManager.GetString("EquipoParrafo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historia.
        /// </summary>
        internal static string HistoriaHeader {
            get {
                return ResourceManager.GetString("HistoriaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En 2008 Seguricel surge como una iniciativa de la empresa ALC Comunicaciones, C.A., la cual ha desarrollado equipos electrónicos para diferentes aplicaciones desde 1991. Inicialmente solo se pretendía abrir las puertas con el celular, pero el proyecto comienza a pivotar por la exigencia del mercado para convertirse en un sistema de seguridad. Seguricel es el producto de cientos de feedback, ideas y objeciones de nuestros amigos, allegados y potenciales clientes que cada vez querían o se les ocurría algo nue [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HistoriaParrafo1 {
            get {
                return ResourceManager.GetString("HistoriaParrafo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En 2012 Seguricel es seleccionado como uno de los emprendimientos tecnológicos más destacados de Lationamérica por el grupo Telefónica a través de su iniciativa Global Wayra, siendo acelerado el proyecto y creada la empresa formalmente como SeguriCel Telemática, C.A. con la participación de Wayra..
        /// </summary>
        internal static string HistoriaParrafo2 {
            get {
                return ResourceManager.GetString("HistoriaParrafo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel es tiene el objetivo de proveer soluciones de seguridad a las comunidades residenciales. Luego de años de desarrollo y bajo el concepto de “Seguridad, Comodidad y Control”, Seguricel  provee soluciones de seguridad fáciles de usar, operando por celular e internet; el producto de la integración de tecnologías actuales en electrónica, informática y telecomunicaciones y ha sido diseñado 100% en Venezuela, específicamente para el problema de la seguridad actual en Latinoamérica. Contamos con una soluc [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string HistoriaParrafo3 {
            get {
                return ResourceManager.GetString("HistoriaParrafo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Misión.
        /// </summary>
        internal static string MisionHeader {
            get {
                return ResourceManager.GetString("MisionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveer a nuestros clientes alternativas innovadoras, seguras e integrales basadas en soluciones telemáticas que puedan satisfacer sus necesidades de seguridad y mejorar su calidad de vida. Ofreciéndoles equipos, sistemas y servicios de la más avanzada tecnología y calidad con rapidez y probada eficiencia. Crear y mantener un equipo de trabajo saludable y emprendedor, con una sana administración que proporcione a sus miembros recompensas financieras, desarrollo y crecimiento personal, esforzándonos en mante [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string MisionParrafo1 {
            get {
                return ResourceManager.GetString("MisionParrafo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Política de Calidad.
        /// </summary>
        internal static string PoliticaCalidadHeader {
            get {
                return ResourceManager.GetString("PoliticaCalidadHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Satisfacción de sus necesidades..
        /// </summary>
        internal static string PoliticaCalidad_Valor1 {
            get {
                return ResourceManager.GetString("PoliticaCalidad_Valor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La puesta en el mercado de sistemas de calidad elaborados con alta tecnología..
        /// </summary>
        internal static string PoliticaCalidad_Valor2 {
            get {
                return ResourceManager.GetString("PoliticaCalidad_Valor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El compromiso de todos los empleados y proveedores de SEGURICEL, adoptarán el principio de hacer las cosas bien hechas  desde la primera vez, siempre..
        /// </summary>
        internal static string PoliticaCalidad_Valor3 {
            get {
                return ResourceManager.GetString("PoliticaCalidad_Valor3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es política de la calidad de SEGURICEL Venezuela brindar absoluta confianza y seguridad a sus clientes mediante:&lt;br /&gt;.
        /// </summary>
        internal static string PolíticaCalidadParrafo1 {
            get {
                return ResourceManager.GetString("PolíticaCalidadParrafo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quiénes somos?, ¿Qué hacemos? y ¿Por qué lo hacemos?.
        /// </summary>
        internal static string SubtituloPagina {
            get {
                return ResourceManager.GetString("SubtituloPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compañía.
        /// </summary>
        internal static string TituloPagina {
            get {
                return ResourceManager.GetString("TituloPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valores.
        /// </summary>
        internal static string ValoresHeader {
            get {
                return ResourceManager.GetString("ValoresHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Honestidad.
        /// </summary>
        internal static string Valores_Valor1 {
            get {
                return ResourceManager.GetString("Valores_Valor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsabilidd.
        /// </summary>
        internal static string Valores_Valor2 {
            get {
                return ResourceManager.GetString("Valores_Valor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calidad.
        /// </summary>
        internal static string Valores_Valor3 {
            get {
                return ResourceManager.GetString("Valores_Valor3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lealtad.
        /// </summary>
        internal static string Valores_Valor4 {
            get {
                return ResourceManager.GetString("Valores_Valor4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visión.
        /// </summary>
        internal static string VisionHeader {
            get {
                return ResourceManager.GetString("VisionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ser líderes consolidados dentro y fuera de Venezuela en soluciones integrales (hardware y software) de telemática para seguridad residencial. Lograr que cada cliente, que cada usuario disfrute realmente de nuestros servicios y se convierta en un fan..
        /// </summary>
        internal static string VisionParrafo1 {
            get {
                return ResourceManager.GetString("VisionParrafo1", resourceCulture);
            }
        }
    }
}
