//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FirmResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FirmResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Seguricel3.App_GlobalResources.Firmware.FirmResource", typeof(FirmResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Firmware.
        /// </summary>
        public static string CreateHeaderPage {
            get {
                return ResourceManager.GetString("CreateHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Nuevo Firmware.
        /// </summary>
        public static string CreatePageTitle {
            get {
                return ResourceManager.GetString("CreatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Firmware.
        /// </summary>
        public static string DeleteHeaderPage {
            get {
                return ResourceManager.GetString("DeleteHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Eliminar Firmware.
        /// </summary>
        public static string DeletePageTitle {
            get {
                return ResourceManager.GetString("DeletePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Firmware.
        /// </summary>
        public static string EditHeaderPage {
            get {
                return ResourceManager.GetString("EditHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Actualizar Firmware.
        /// </summary>
        public static string EditPageTitle {
            get {
                return ResourceManager.GetString("EditPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimiento de Firmware.
        /// </summary>
        public static string HeaderPage {
            get {
                return ResourceManager.GetString("HeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string labelDescripcionFirmware {
            get {
                return ResourceManager.GetString("labelDescripcionFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Publicación.
        /// </summary>
        public static string labelFirmware_FechaPublicacion {
            get {
                return ResourceManager.GetString("labelFirmware_FechaPublicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Firmware.
        /// </summary>
        public static string labelFirmware_Firmware {
            get {
                return ResourceManager.GetString("labelFirmware_Firmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Firmware.
        /// </summary>
        public static string labelFirmware_IdFirmware {
            get {
                return ResourceManager.GetString("labelFirmware_IdFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string labelId {
            get {
                return ResourceManager.GetString("labelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string labelNombre {
            get {
                return ResourceManager.GetString("labelNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de dispositivo.
        /// </summary>
        public static string labelTipoDispositivo {
            get {
                return ResourceManager.GetString("labelTipoDispositivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión.
        /// </summary>
        public static string labelVersionFirmware {
            get {
                return ResourceManager.GetString("labelVersionFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Mantenimiento de Firmware.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
    }
}
