//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModuloResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModuloResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Seguricel3.App_GlobalResources.Seguridad.Modulo.ModuloResource", typeof(ModuloResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Módulo.
        /// </summary>
        public static string CreateModuloHeaderPage {
            get {
                return ResourceManager.GetString("CreateModuloHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Nuevo Módulo.
        /// </summary>
        public static string CreateModuloPageTitle {
            get {
                return ResourceManager.GetString("CreateModuloPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Módulo.
        /// </summary>
        public static string EditModuloHeaderPage {
            get {
                return ResourceManager.GetString("EditModuloHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Actualizar Módulo.
        /// </summary>
        public static string EditModuloPageTitle {
            get {
                return ResourceManager.GetString("EditModuloPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string labelModulo {
            get {
                return ResourceManager.GetString("labelModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Action.
        /// </summary>
        public static string labelModuloAction {
            get {
                return ResourceManager.GetString("labelModuloAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        public static string labelModuloActivo {
            get {
                return ResourceManager.GetString("labelModuloActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Controlador.
        /// </summary>
        public static string labelModuloController {
            get {
                return ResourceManager.GetString("labelModuloController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string labelModuloNombre {
            get {
                return ResourceManager.GetString("labelModuloNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Módulo Padre.
        /// </summary>
        public static string labelModuloPadre {
            get {
                return ResourceManager.GetString("labelModuloPadre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Elemento.
        /// </summary>
        public static string labelModuloTipoElemento {
            get {
                return ResourceManager.GetString("labelModuloTipoElemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Módulos del Sistema.
        /// </summary>
        public static string ModulosHeaderPage {
            get {
                return ResourceManager.GetString("ModulosHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Módulos del Sistema.
        /// </summary>
        public static string ModulosPageTitle {
            get {
                return ResourceManager.GetString("ModulosPageTitle", resourceCulture);
            }
        }
    }
}
