//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TablasResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TablasResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Seguricel3.App_GlobalResources.Tablas.TablasResource", typeof(TablasResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudades.
        /// </summary>
        public static string CiudadHeaderPage {
            get {
                return ResourceManager.GetString("CiudadHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Ciudades.
        /// </summary>
        public static string CiudadPageTitle {
            get {
                return ResourceManager.GetString("CiudadPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Ciudades.
        /// </summary>
        public static string CiudadTableHeader {
            get {
                return ResourceManager.GetString("CiudadTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Ciudad en el Estado.
        /// </summary>
        public static string CreateCiudadHeaderPage {
            get {
                return ResourceManager.GetString("CreateCiudadHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Nueva Ciudad.
        /// </summary>
        public static string CreateCiudadPageTitle {
            get {
                return ResourceManager.GetString("CreateCiudadPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Estado en el País.
        /// </summary>
        public static string CreateEstadoHeaderPage {
            get {
                return ResourceManager.GetString("CreateEstadoHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Nuevo Estado.
        /// </summary>
        public static string CreateEstadoPageTitle {
            get {
                return ResourceManager.GetString("CreateEstadoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Grupo.
        /// </summary>
        public static string CreateGrupoHeaderPage {
            get {
                return ResourceManager.GetString("CreateGrupoHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Nuevo Grupo.
        /// </summary>
        public static string CreateGrupoPageTitle {
            get {
                return ResourceManager.GetString("CreateGrupoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Pais.
        /// </summary>
        public static string CreatePaisHeaderPage {
            get {
                return ResourceManager.GetString("CreatePaisHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Nuevo Pais.
        /// </summary>
        public static string CreatePaisPageTitle {
            get {
                return ResourceManager.GetString("CreatePaisPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo SubGrupo en el Grupo.
        /// </summary>
        public static string CreateSubGrupoHeaderPage {
            get {
                return ResourceManager.GetString("CreateSubGrupoHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Nuevo SubGrupo.
        /// </summary>
        public static string CreateSubGrupoPageTitle {
            get {
                return ResourceManager.GetString("CreateSubGrupoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Tipo de Acción.
        /// </summary>
        public static string CreateTipoAccionHeaderPage {
            get {
                return ResourceManager.GetString("CreateTipoAccionHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Nuevo Tipo de Acción.
        /// </summary>
        public static string CreateTipoAccionPageTitle {
            get {
                return ResourceManager.GetString("CreateTipoAccionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Tipo de Anuncio.
        /// </summary>
        public static string CreateTipoAnuncioHeaderPage {
            get {
                return ResourceManager.GetString("CreateTipoAnuncioHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Nuevo Tipo de Anuncio.
        /// </summary>
        public static string CreateTipoAnuncioPageTitle {
            get {
                return ResourceManager.GetString("CreateTipoAnuncioPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Tipo de Bandeja.
        /// </summary>
        public static string CreateTipoBandejaHeaderPage {
            get {
                return ResourceManager.GetString("CreateTipoBandejaHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Nuevo Tipo de Bandeja.
        /// </summary>
        public static string CreateTipoBandejaPageTitle {
            get {
                return ResourceManager.GetString("CreateTipoBandejaPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Tipo de Cargo en Junta de Condominio.
        /// </summary>
        public static string CreateTipoCargoJuntaCondominioHeaderPage {
            get {
                return ResourceManager.GetString("CreateTipoCargoJuntaCondominioHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Nuevo Tipo de Cargo en Junta de Condominio.
        /// </summary>
        public static string CreateTipoCargoJuntaCondominioPageTitle {
            get {
                return ResourceManager.GetString("CreateTipoCargoJuntaCondominioPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Tipo de Cartelera.
        /// </summary>
        public static string CreateTipoCarteleraHeaderPage {
            get {
                return ResourceManager.GetString("CreateTipoCarteleraHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Nuevo Tipo de Cartelera.
        /// </summary>
        public static string CreateTipoCarteleraPageTitle {
            get {
                return ResourceManager.GetString("CreateTipoCarteleraPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Nuevo Tipo de Cartelera.
        /// </summary>
        public static string CreateTipoCarteleraTableHeader {
            get {
                return ResourceManager.GetString("CreateTipoCarteleraTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Tipo de Contacto.
        /// </summary>
        public static string CreateTipoContactoHeaderPage {
            get {
                return ResourceManager.GetString("CreateTipoContactoHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Nuevo Tipo de Contacto.
        /// </summary>
        public static string CreateTipoContactoPageTitle {
            get {
                return ResourceManager.GetString("CreateTipoContactoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Nuevo Tipo de Contacto.
        /// </summary>
        public static string CreateTipoContactoTableHeader {
            get {
                return ResourceManager.GetString("CreateTipoContactoTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Tipo de Dispositivo.
        /// </summary>
        public static string CreateTipoDispositivoHeaderPage {
            get {
                return ResourceManager.GetString("CreateTipoDispositivoHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Nuevo Tipo de Dispositivo.
        /// </summary>
        public static string CreateTipoDispositivoPageTitle {
            get {
                return ResourceManager.GetString("CreateTipoDispositivoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Tipo de Mensaje.
        /// </summary>
        public static string CreateTipoMensajeHeaderPage {
            get {
                return ResourceManager.GetString("CreateTipoMensajeHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Nuevo Tipo de Mensaje.
        /// </summary>
        public static string CreateTipoMensajePageTitle {
            get {
                return ResourceManager.GetString("CreateTipoMensajePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Tipo de Persona.
        /// </summary>
        public static string CreateTipoPersonaHeaderPage {
            get {
                return ResourceManager.GetString("CreateTipoPersonaHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Nuevo Tipo de Persona.
        /// </summary>
        public static string CreateTipoPersonaPageTitle {
            get {
                return ResourceManager.GetString("CreateTipoPersonaPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Tipo de Propuesta.
        /// </summary>
        public static string CreateTipoPropuestaHeaderPage {
            get {
                return ResourceManager.GetString("CreateTipoPropuestaHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Nuevo Tipo de Propuesta.
        /// </summary>
        public static string CreateTipoPropuestaPageTitle {
            get {
                return ResourceManager.GetString("CreateTipoPropuestaPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Tipo de Ticket.
        /// </summary>
        public static string CreateTipoTicketHeaderPage {
            get {
                return ResourceManager.GetString("CreateTipoTicketHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Nuevo Tipo de Ticket.
        /// </summary>
        public static string CreateTipoTicketPageTitle {
            get {
                return ResourceManager.GetString("CreateTipoTicketPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Tipo de Usuario.
        /// </summary>
        public static string CreateTipoUsuarioHeaderPage {
            get {
                return ResourceManager.GetString("CreateTipoUsuarioHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Nuevo Tipo de Usuario.
        /// </summary>
        public static string CreateTipoUsuarioPageTitle {
            get {
                return ResourceManager.GetString("CreateTipoUsuarioPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Tipo de Vehiculo.
        /// </summary>
        public static string CreateTipoVehiculoHeaderPage {
            get {
                return ResourceManager.GetString("CreateTipoVehiculoHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Nuevo Tipo de Vehiculo.
        /// </summary>
        public static string CreateTipoVehiculoPageTitle {
            get {
                return ResourceManager.GetString("CreateTipoVehiculoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Ciudad en el Estado.
        /// </summary>
        public static string EditCiudadHeaderPage {
            get {
                return ResourceManager.GetString("EditCiudadHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Actualizar Ciudad.
        /// </summary>
        public static string EditCiudadPageTitle {
            get {
                return ResourceManager.GetString("EditCiudadPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Estado en el País.
        /// </summary>
        public static string EditEstadoHeaderPage {
            get {
                return ResourceManager.GetString("EditEstadoHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Actualizar Estado.
        /// </summary>
        public static string EditEstadoPageTitle {
            get {
                return ResourceManager.GetString("EditEstadoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Grupo.
        /// </summary>
        public static string EditGrupoHeaderPage {
            get {
                return ResourceManager.GetString("EditGrupoHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Actualizar Grupo.
        /// </summary>
        public static string EditGrupoPageTitle {
            get {
                return ResourceManager.GetString("EditGrupoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Pais.
        /// </summary>
        public static string EditPaisHeaderPage {
            get {
                return ResourceManager.GetString("EditPaisHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Actualizar Pais.
        /// </summary>
        public static string EditPaisPageTitle {
            get {
                return ResourceManager.GetString("EditPaisPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar SubGrupo del Grupo .
        /// </summary>
        public static string EditSubGrupoHeaderPage {
            get {
                return ResourceManager.GetString("EditSubGrupoHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Actualizar SubGrupo.
        /// </summary>
        public static string EditSubGrupoPageTitle {
            get {
                return ResourceManager.GetString("EditSubGrupoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Tipo de Acción.
        /// </summary>
        public static string EditTipoAccionHeaderPage {
            get {
                return ResourceManager.GetString("EditTipoAccionHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Actualizar Tipo de Acción.
        /// </summary>
        public static string EditTipoAccionPageTitle {
            get {
                return ResourceManager.GetString("EditTipoAccionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Tipo de Anuncio.
        /// </summary>
        public static string EditTipoAnuncioHeaderPage {
            get {
                return ResourceManager.GetString("EditTipoAnuncioHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Actualizar Tipo de Anuncio.
        /// </summary>
        public static string EditTipoAnuncioPageTitle {
            get {
                return ResourceManager.GetString("EditTipoAnuncioPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Tipo de Bandeja.
        /// </summary>
        public static string EditTipoBandejaHeaderPage {
            get {
                return ResourceManager.GetString("EditTipoBandejaHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Actualizar Tipo de Bandeja.
        /// </summary>
        public static string EditTipoBandejaPageTitle {
            get {
                return ResourceManager.GetString("EditTipoBandejaPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Tipo de Cargo en Junta de Condominio.
        /// </summary>
        public static string EditTipoCargoJuntaCondominioHeaderPage {
            get {
                return ResourceManager.GetString("EditTipoCargoJuntaCondominioHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Actualizar Tipo de Cargo en Junta de Condominio.
        /// </summary>
        public static string EditTipoCargoJuntaCondominioPageTitle {
            get {
                return ResourceManager.GetString("EditTipoCargoJuntaCondominioPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Tipo de Cartelera.
        /// </summary>
        public static string EditTipoCarteleraHeaderPage {
            get {
                return ResourceManager.GetString("EditTipoCarteleraHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Actualizar Tipo de Cartelera.
        /// </summary>
        public static string EditTipoCarteleraPageTitle {
            get {
                return ResourceManager.GetString("EditTipoCarteleraPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Actualizar Tipo de Cartelera.
        /// </summary>
        public static string EditTipoCarteleraTableHeader {
            get {
                return ResourceManager.GetString("EditTipoCarteleraTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Tipo de Contacto.
        /// </summary>
        public static string EditTipoContactoHeaderPage {
            get {
                return ResourceManager.GetString("EditTipoContactoHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Actualizar Tipo de Contacto.
        /// </summary>
        public static string EditTipoContactoPageTitle {
            get {
                return ResourceManager.GetString("EditTipoContactoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Actualizar Tipo de Contacto.
        /// </summary>
        public static string EditTipoContactoTableHeader {
            get {
                return ResourceManager.GetString("EditTipoContactoTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Tipo de Dispositivo.
        /// </summary>
        public static string EditTipoDispositivoHeaderPage {
            get {
                return ResourceManager.GetString("EditTipoDispositivoHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Actualizar Tipo de Dispositivo.
        /// </summary>
        public static string EditTipoDispositivoPageTitle {
            get {
                return ResourceManager.GetString("EditTipoDispositivoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Tipo de Mensaje.
        /// </summary>
        public static string EditTipoMensajeHeaderPage {
            get {
                return ResourceManager.GetString("EditTipoMensajeHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Actualizar Tipo de Mensaje.
        /// </summary>
        public static string EditTipoMensajePageTitle {
            get {
                return ResourceManager.GetString("EditTipoMensajePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Tipo de Persona.
        /// </summary>
        public static string EditTipoPersonaHeaderPage {
            get {
                return ResourceManager.GetString("EditTipoPersonaHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Actualizar Tipo de Persona.
        /// </summary>
        public static string EditTipoPersonaPageTitle {
            get {
                return ResourceManager.GetString("EditTipoPersonaPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Tipo de Propuesta.
        /// </summary>
        public static string EditTipoPropuestaHeaderPage {
            get {
                return ResourceManager.GetString("EditTipoPropuestaHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Actualizar Tipo de Propuesta.
        /// </summary>
        public static string EditTipoPropuestaPageTitle {
            get {
                return ResourceManager.GetString("EditTipoPropuestaPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Tipo de Ticket.
        /// </summary>
        public static string EditTipoTicketHeaderPage {
            get {
                return ResourceManager.GetString("EditTipoTicketHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Actualizar Tipo de Ticket.
        /// </summary>
        public static string EditTipoTicketPageTitle {
            get {
                return ResourceManager.GetString("EditTipoTicketPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Tipo de Usuario.
        /// </summary>
        public static string EditTipoUsuarioHeaderPage {
            get {
                return ResourceManager.GetString("EditTipoUsuarioHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Actualizar Tipo de Usuario.
        /// </summary>
        public static string EditTipoUsuarioPageTitle {
            get {
                return ResourceManager.GetString("EditTipoUsuarioPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Tipo de Vehiculo.
        /// </summary>
        public static string EditTipoVehiculoHeaderPage {
            get {
                return ResourceManager.GetString("EditTipoVehiculoHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Actualizar Tipo de Vehiculo.
        /// </summary>
        public static string EditTipoVehiculoPageTitle {
            get {
                return ResourceManager.GetString("EditTipoVehiculoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estados.
        /// </summary>
        public static string EstadoHeaderPage {
            get {
                return ResourceManager.GetString("EstadoHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Estados.
        /// </summary>
        public static string EstadoPageTitle {
            get {
                return ResourceManager.GetString("EstadoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Estados.
        /// </summary>
        public static string EstadoTableHeader {
            get {
                return ResourceManager.GetString("EstadoTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupos.
        /// </summary>
        public static string GrupoHeaderPage {
            get {
                return ResourceManager.GetString("GrupoHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Grupos.
        /// </summary>
        public static string GrupoPageTitle {
            get {
                return ResourceManager.GetString("GrupoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Grupos.
        /// </summary>
        public static string GrupoTableHeader {
            get {
                return ResourceManager.GetString("GrupoTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activa.
        /// </summary>
        public static string labelActivoCiudad {
            get {
                return ResourceManager.GetString("labelActivoCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        public static string labelActivoEstado {
            get {
                return ResourceManager.GetString("labelActivoEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        public static string labelActivoPais {
            get {
                return ResourceManager.GetString("labelActivoPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        public static string labelCiudad {
            get {
                return ResourceManager.GetString("labelCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string labelCodigoGrupo {
            get {
                return ResourceManager.GetString("labelCodigoGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string labelCodigoSubGrupo {
            get {
                return ResourceManager.GetString("labelCodigoSubGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string labelEstado {
            get {
                return ResourceManager.GetString("labelEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string labelId {
            get {
                return ResourceManager.GetString("labelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Latitud.
        /// </summary>
        public static string labelLatitud {
            get {
                return ResourceManager.GetString("labelLatitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud.
        /// </summary>
        public static string labelLongitud {
            get {
                return ResourceManager.GetString("labelLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string labelNombre {
            get {
                return ResourceManager.GetString("labelNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string labelNombreCiudad {
            get {
                return ResourceManager.GetString("labelNombreCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cultura.
        /// </summary>
        public static string labelNombreCulture {
            get {
                return ResourceManager.GetString("labelNombreCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string labelNombreEstado {
            get {
                return ResourceManager.GetString("labelNombreEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string labelNombreGrupo {
            get {
                return ResourceManager.GetString("labelNombreGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string labelNombrePais {
            get {
                return ResourceManager.GetString("labelNombrePais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string labelNombreSubGrupo {
            get {
                return ResourceManager.GetString("labelNombreSubGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País.
        /// </summary>
        public static string labelPais {
            get {
                return ResourceManager.GetString("labelPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo.
        /// </summary>
        public static string labelSubGrupo_IdGrupo {
            get {
                return ResourceManager.GetString("labelSubGrupo_IdGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paises.
        /// </summary>
        public static string PaisHeaderPage {
            get {
                return ResourceManager.GetString("PaisHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Paises.
        /// </summary>
        public static string PaisPageTitle {
            get {
                return ResourceManager.GetString("PaisPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Paises.
        /// </summary>
        public static string PaisTableHeader {
            get {
                return ResourceManager.GetString("PaisTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor presione el botón para obtener las coodenadas.
        /// </summary>
        public static string RequiredPressButton {
            get {
                return ResourceManager.GetString("RequiredPressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SubGrupos.
        /// </summary>
        public static string SubGrupoHeaderPage {
            get {
                return ResourceManager.GetString("SubGrupoHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - SubGrupos.
        /// </summary>
        public static string SubGrupoPageTitle {
            get {
                return ResourceManager.GetString("SubGrupoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de SubGrupos.
        /// </summary>
        public static string SubGrupoTableHeader {
            get {
                return ResourceManager.GetString("SubGrupoTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de Acción.
        /// </summary>
        public static string TipoAccionHeaderPage {
            get {
                return ResourceManager.GetString("TipoAccionHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Tipos de Acción.
        /// </summary>
        public static string TipoAccionPageTitle {
            get {
                return ResourceManager.GetString("TipoAccionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Tipos de Acción.
        /// </summary>
        public static string TipoAccionTableHeader {
            get {
                return ResourceManager.GetString("TipoAccionTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de Anuncio.
        /// </summary>
        public static string TipoAnuncioHeaderPage {
            get {
                return ResourceManager.GetString("TipoAnuncioHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Tipos de Anuncio.
        /// </summary>
        public static string TipoAnuncioPageTitle {
            get {
                return ResourceManager.GetString("TipoAnuncioPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Tipos de Anuncio.
        /// </summary>
        public static string TipoAnuncioTableHeader {
            get {
                return ResourceManager.GetString("TipoAnuncioTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de Bandeja.
        /// </summary>
        public static string TipoBandejaHeaderPage {
            get {
                return ResourceManager.GetString("TipoBandejaHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Tipos de Bandeja.
        /// </summary>
        public static string TipoBandejaPageTitle {
            get {
                return ResourceManager.GetString("TipoBandejaPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Tipos de Bandeja.
        /// </summary>
        public static string TipoBandejaTableHeader {
            get {
                return ResourceManager.GetString("TipoBandejaTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de Cargo en Junta de Condominio.
        /// </summary>
        public static string TipoCargoJuntaCondominioHeaderPage {
            get {
                return ResourceManager.GetString("TipoCargoJuntaCondominioHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Tipos de Cargo en Junta de Condominio.
        /// </summary>
        public static string TipoCargoJuntaCondominioPageTitle {
            get {
                return ResourceManager.GetString("TipoCargoJuntaCondominioPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Tipos de Cargo en Junta de Condominio.
        /// </summary>
        public static string TipoCargoJuntaCondominioTableHeader {
            get {
                return ResourceManager.GetString("TipoCargoJuntaCondominioTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de Cartelera.
        /// </summary>
        public static string TipoCarteleraHeaderPage {
            get {
                return ResourceManager.GetString("TipoCarteleraHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Tipos de Cartelera.
        /// </summary>
        public static string TipoCarteleraPageTitle {
            get {
                return ResourceManager.GetString("TipoCarteleraPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Tipos de Cartelera.
        /// </summary>
        public static string TipoCarteleraTableHeader {
            get {
                return ResourceManager.GetString("TipoCarteleraTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de Contacto.
        /// </summary>
        public static string TipoContactoHeaderPage {
            get {
                return ResourceManager.GetString("TipoContactoHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Tipos de Contacto.
        /// </summary>
        public static string TipoContactoPageTitle {
            get {
                return ResourceManager.GetString("TipoContactoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Tipos de Contacto.
        /// </summary>
        public static string TipoContactoTableHeader {
            get {
                return ResourceManager.GetString("TipoContactoTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de Contrato.
        /// </summary>
        public static string TipoContratoHeaderPage {
            get {
                return ResourceManager.GetString("TipoContratoHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Tipos de Contrato.
        /// </summary>
        public static string TipoContratoPageTitle {
            get {
                return ResourceManager.GetString("TipoContratoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Tipos de Contrato.
        /// </summary>
        public static string TipoContratoTableHeader {
            get {
                return ResourceManager.GetString("TipoContratoTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de Dispositivo.
        /// </summary>
        public static string TipoDispositivoHeaderPage {
            get {
                return ResourceManager.GetString("TipoDispositivoHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Tipos de Dispositivo.
        /// </summary>
        public static string TipoDispositivoPageTitle {
            get {
                return ResourceManager.GetString("TipoDispositivoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Tipos de Dispositivo.
        /// </summary>
        public static string TipoDispositivoTableHeader {
            get {
                return ResourceManager.GetString("TipoDispositivoTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de Mensaje.
        /// </summary>
        public static string TipoMensajeHeaderPage {
            get {
                return ResourceManager.GetString("TipoMensajeHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Tipos de Mensaje.
        /// </summary>
        public static string TipoMensajePageTitle {
            get {
                return ResourceManager.GetString("TipoMensajePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Tipos de Mensaje.
        /// </summary>
        public static string TipoMensajeTableHeader {
            get {
                return ResourceManager.GetString("TipoMensajeTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de Persona.
        /// </summary>
        public static string TipoPersonaHeaderPage {
            get {
                return ResourceManager.GetString("TipoPersonaHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Tipos de Persona.
        /// </summary>
        public static string TipoPersonaPageTitle {
            get {
                return ResourceManager.GetString("TipoPersonaPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Tipos de Persona.
        /// </summary>
        public static string TipoPersonaTableHeader {
            get {
                return ResourceManager.GetString("TipoPersonaTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de Propuesta.
        /// </summary>
        public static string TipoPropuestaHeaderPage {
            get {
                return ResourceManager.GetString("TipoPropuestaHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Tipos de Propuesta.
        /// </summary>
        public static string TipoPropuestaPageTitle {
            get {
                return ResourceManager.GetString("TipoPropuestaPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Tipos de Propuesta.
        /// </summary>
        public static string TipoPropuestaTableHeader {
            get {
                return ResourceManager.GetString("TipoPropuestaTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de Ticket.
        /// </summary>
        public static string TipoTicketHeaderPage {
            get {
                return ResourceManager.GetString("TipoTicketHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Tipos de Ticket.
        /// </summary>
        public static string TipoTicketPageTitle {
            get {
                return ResourceManager.GetString("TipoTicketPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Tipos de Ticket.
        /// </summary>
        public static string TipoTicketTableHeader {
            get {
                return ResourceManager.GetString("TipoTicketTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de Usuario.
        /// </summary>
        public static string TipoUsuarioHeaderPage {
            get {
                return ResourceManager.GetString("TipoUsuarioHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Tipos de Usuario.
        /// </summary>
        public static string TipoUsuarioPageTitle {
            get {
                return ResourceManager.GetString("TipoUsuarioPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Tipos de Usuario.
        /// </summary>
        public static string TipoUsuarioTableHeader {
            get {
                return ResourceManager.GetString("TipoUsuarioTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de Vehiculo.
        /// </summary>
        public static string TipoVehiculoHeaderPage {
            get {
                return ResourceManager.GetString("TipoVehiculoHeaderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguricel - Tipos de Vehiculo.
        /// </summary>
        public static string TipoVehiculoPageTitle {
            get {
                return ResourceManager.GetString("TipoVehiculoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Tipos de Vehiculo.
        /// </summary>
        public static string TipoVehiculoTableHeader {
            get {
                return ResourceManager.GetString("TipoVehiculoTableHeader", resourceCulture);
            }
        }
    }
}
